function point_param_type(mat::AbstractMaterial)
    return throw(InterfaceError(mat, "point_param_type", params_macro_hint(mat)))
end

# point parameters that are not generic in their float type, i.e. ones that are not
# generated by `@params`, ignore the requested float type
point_param_type(mat::AbstractMaterial, ::Type) = point_param_type(mat)

"""
    instantiate_point_params(P, FT)

$(internal_api_warning())

Return the instantiation of a point parameter type with the float type `FT` of the
simulation. Point parameters generated by [`@params`](@ref) are generic in their float type,
a hand-written type usually is not, and `point_param_type` has to answer with a concrete
type either way, because `Body` and `BodyChunk` are parameterized with it.
"""
@inline function instantiate_point_params(::Type{P}, ::Type{FT}) where {P,FT}
    P isa UnionAll || return P
    return P{FT}
end

# the linked type may carry marker fields, whose type parameters only the models of the
# material can answer -- the registered declarations say which parameters the type has
function instantiate_point_params(mat, ::Type{P}, ::Type{FT}) where {P,FT}
    P isa UnionAll || return P
    spec = try
        param_fields_expr(P)
    catch
        nothing
    end
    isnothing(spec) && return P{FT}
    args = Any[]
    params_use_sim_float(spec) && push!(args, FT)
    if any(is_cm_param_decl, spec.decls)
        push!(args, constitutive_param_type(get_constitutive_model(mat), FT))
    end
    if any(is_dmg_param_decl, spec.decls)
        push!(args, damage_param_type(get_dmgmodel(mat), FT))
    end
    isempty(args) && return P
    return P{args...}
end

function get_point_params(mat::AbstractMaterial, ::Dict{Symbol,Any})
    return throw(InterfaceError(mat, "get_point_params", params_macro_hint(mat)))
end

function required_point_parameters(mat::Type{<:AbstractMaterial})
    return throw(InterfaceError(mat, "required_point_parameters", family_method_hint()))
end

function allowed_material_kwargs(mat::AbstractMaterial)
    return throw(InterfaceError(mat, "allowed_material_kwargs", params_macro_hint(mat)))
end

function params_macro_hint(mat)
    name = mat isa Type ? nameof(mat) : nameof(typeof(mat))
    msg = "Declare the point parameters of `$(name)` with `@params`, e.g.\n"
    msg *= "        Peridynamics.@params $(name) struct MyPointParameters\n"
    msg *= "            @inherit StandardParameters\n"
    msg *= "        end\n"
    msg *= "    which defines `point_param_type`, `get_point_params` and "
    msg *= "`allowed_material_kwargs` for you."
    return msg
end

function family_method_hint()
    msg = "This method is defined for every material family of this package, so a material "
    msg *= "that\n    subtypes a family, e.g. `AbstractBondSystemMaterial{NoCorrection}`, "
    msg *= "inherits it. Define\n    it directly only when introducing a new family."
    return msg
end

"""
    @params material struct PointParameters ... end
    @params material PointParameters begin ... end
    @params material PointParameters

$(extension_api_note())

Declare the point parameters of a material, i.e. the values `material!` assigns to a point
set. The first form defines a new point parameter type, the second defines another
constructor of an existing one for `material`, and the third links a hand-written type.

The macro generates the struct, the constructor that reads the keywords of `material!`, the
converting constructor between float types, `point_param_type`, `get_point_params`,
`allowed_material_kwargs` and the `log_param_property` methods, so that these cannot drift
apart from each other.

# Declaring a parameter

| declaration | meaning |
|:---|:---|
| `rho` | required keyword `rho` |
| `sigma_y = Inf` | keyword `sigma_y`, defaulting to `Inf` |
| `C1 = 30 * μ / (π * δ^4)` | keyword `C1`, defaulting to an expression of the parameters before it |
| `n::Int = 4` | keyword pinned to a concrete type |
| `@kwarg gamma_c gammac = 1e-10` | keyword name differs from the parameter name |
| `@derived bc = 18 * K / (π * δ^4)` | computed, **not** a keyword |
| `@derived (; Gc, εc) = get_frac_params(mat.dmgmodel, δ, K; Gc, epsilon_c)` | a group of parameters computed by one call |
| `@log "shear modulus" G` | also write the parameter to the simulation log |
| `@inherit StandardParameters` | include the declarations of another block |

Every right-hand side follows one rule:

| position | meaning |
|:---|:---|
| before `;` | the parameters declared above, `mat`, and anything in scope of the module |
| after `;` | names of `material!` keywords, in shorthand |

This is one rule for a constant default, a value derived from other parameters and a call
that supplies a whole group, and it is why the order of the declarations matters. See
[`@derived`](@ref).

A parameter declared without a type follows the float type of the simulation, which is what
makes the generated struct parametric:

```julia
struct StandardPointParameters{FT<:Real} <: AbstractPointParameters
    δ::FT
    rho::FT
    ...
end
```

`Peridynamics.point_param_type(mat)` returns the instantiation with the float type of the
simulation and `Peridynamics.point_param_type(mat, Float32)` the `Float32` one. A parameter
declared with a concrete type, e.g. `n::Int`, keeps that type for every simulation.

# Reusing parameters with `@inherit`

[`@inherit`](@ref) includes all parameters of another point parameter type or of a parameter
block defined with [`@params_fields`](@ref), with the merge rules of `@storage`: two
`@inherit`s may contribute the same parameter only if they declare it identically, and a
declaration in the body overrides an inherited one in place.

```julia
Peridynamics.@params MyMaterial struct MyPointParameters
    @inherit StandardParameters
    @log "yield stress" sigma_y = Inf
    hardening = 0.0
end
```

The package ships the parameter blocks `DiscretizationParameters`, `ElasticParameters`,
`BBElasticParameters`, `FractureParameters`, `BondHorizonParameters`,
`InteractionParameters` and `StandardParameters`, each documented with the parameters it
exposes. Names inside the definition are resolved in the module of the
definition first and in `Peridynamics` second, so they need no import.

Own blocks are declared with [`@params_fields`](@ref).
"""
macro params(params_expr)
    macrocheck_input_params_struct(params_expr)
    return __params_type(params_expr, __module__).exprs
end

macro params(material, params)
    macrocheck_input_material(material)
    if params isa Expr && params.head === :struct
        return __params_struct(material, params, __module__)
    end
    macrocheck_input_params(params)
    return __params_link(material, params)
end

macro params(material, params, block)
    macrocheck_input_material(material)
    macrocheck_input_params(params)
    macrocheck_input_params_block(block)
    return __params_constructor(material, params, block, __module__)
end

#=
Whether a definition binds the point parameters to a material, i.e. whether it defines
`point_param_type`, `get_point_params` and `allowed_material_kwargs`, follows from the
material it is written for. A material family is abstract and cannot be bound, because those
three methods are part of the contract of a *concrete* material and binding a family would
answer them for every material of it, including the ones that never declared any parameters.
A family can still share a constructor, which is what the generic constructor of
`StandardPointParameters` is.
=#
function is_material_family(material, mod::Module)
    resolved = resolve_in_mod_or_peridynamics(mod, material)
    return isa(resolved, Type) && isabstracttype(resolved)
end

# --------------------------------------------------------------------------------------
# `@params material PointParameters` -- link a hand-written point parameter type
# --------------------------------------------------------------------------------------

function __params_link(material, params)
    local _pre_checks = quote
        Peridynamics.typecheck_material($(esc(material)))
        Peridynamics.typecheck_params($(esc(material)), $(esc(params)))
    end
    local _pointparam_type = quote
        function Peridynamics.point_param_type(mat::$(esc(material)),
                                               ::Base.Type{$(FLOAT_TYPE_PARAM)}=Peridynamics.default_float_type()) where {$(FLOAT_TYPE_PARAM)}
            return Peridynamics.instantiate_point_params(mat, $(esc(params)),
                                                         $(FLOAT_TYPE_PARAM))
        end
    end
    local _get_pointparams = quote
        function Peridynamics.get_point_params(mat::$(esc(material)),
                                               p::Base.Dict{Base.Symbol,Base.Any})
            return $(esc(params))(mat, p)
        end
    end
    local _post_checks = quote
        Peridynamics.constructor_check($(esc(material)), $(esc(params)))
    end
    return Expr(:block, _pre_checks, _pointparam_type, _get_pointparams, _post_checks)
end

# --------------------------------------------------------------------------------------
# `@params material struct PointParameters ... end` -- define everything
# --------------------------------------------------------------------------------------

function __params_type(params_expr, mod::Module)
    local _name, _supertype = get_params_header(params_expr)
    local _spec = get_param_decls(params_expr.args[3].args, mod)
    isempty(_spec.decls) && throw(ArgumentError(empty_params_msg(_name)))
    local _sim_float = params_use_sim_float(_spec)

    local _struct = params_struct_expr(params_expr, _name, _supertype, _spec, _sim_float)
    local _convert = params_convert_expr(_name, _spec, _sim_float)
    local _fields_expr = quote
        function Peridynamics.param_fields_expr(::Base.Type{<:$(esc(_name))})
            return $(QuoteNode(_spec))
        end
    end
    local _logs = param_log_methods(_spec, _name)
    local _markers = params_marker_exprs(_name, _spec)
    # the docstring is attached last, so that a `$(block_table(Name))` in it can already read
    # the declarations that were just registered
    local _doc = quote
        Base.@__doc__ $(esc(_name))
    end
    local _exprs = Expr(:block, _struct, _convert, _fields_expr, _logs..., _markers..., _doc)
    return (; exprs=_exprs, name=_name, spec=_spec, sim_float=_sim_float)
end

function __params_struct(material, params_expr, mod::Module)
    is_material_family(material, mod) && throw(ArgumentError(family_struct_msg(material)))
    local _type = __params_type(params_expr, mod)
    local _constructor = params_constructor_expr(material, _type.name, _type.spec,
                                                 _type.sim_float)
    local _interface = params_interface_exprs(material, _type.name, _type.spec,
                                              _type.sim_float)
    # emitted last, so that `@test_throws` sees the errors of the declarations first
    local _checks = quote
        Peridynamics.typecheck_material($(esc(material)))
        Peridynamics.typecheck_params($(esc(material)), $(esc(_type.name)))
    end
    return Expr(:block, _type.exprs, _constructor, _interface..., _checks)
end

function family_struct_msg(material)
    msg = "`$(material)` is a material family and cannot be bound to point parameters!\n"
    msg *= "  Binding a family would answer `point_param_type` for every material of it, "
    msg *= "including the ones that declare no parameters. Define the type on its own and "
    msg *= "give the family a constructor:\n"
    msg *= "        Peridynamics.@params struct MyPointParameters ... end\n"
    msg *= "        Peridynamics.@params $(material) MyPointParameters begin ... end\n"
    return msg
end

function get_params_header(params_expr)
    header = params_expr.args[2]
    if header isa Symbol
        # case `struct MyPointParameters`
        return header, :(Peridynamics.AbstractPointParameters)
    elseif header isa Expr && header.head === :(<:) && header.args[1] isa Symbol
        # case `struct MyPointParameters <: AbstractPointParameters`
        return header.args[1], header.args[2]
    end
    return throw(ArgumentError(params_header_msg(header)))
end

function params_header_msg(header)
    is_parametric = header isa Expr &&
                    (header.head === :curly ||
                     (header.head === :(<:) && header.args[1] isa Expr &&
                      header.args[1].head === :curly))
    is_parametric || return "point parameter header `$(header)` not supported!\n"
    msg = "point parameters cannot declare their own type parameters, got `$(header)`!\n"
    msg *= "  `@params` derives the type parameters from the declarations, so that the "
    msg *= "point parameters are generic in the float type of the simulation. Declare them "
    msg *= "without type parameters, and give a parameter a concrete type only to pin it, "
    msg *= "e.g.\n"
    msg *= "        n_substeps::Int\n"
    return msg
end

function empty_params_msg(name)
    msg = "the point parameters `$(name)` declare no parameter at all!\n"
    msg *= "  Inherit the parameters of the material family, e.g. `@inherit "
    msg *= "StandardParameters`.\n"
    return msg
end

#=
The generated constructor is the constructor that used to be written by hand, so nothing
about the values it computes or the order in which it computes them changes. `mat` and `p`
are escaped, because the `@from` and default expressions of the declarations are escaped and
have to see them.
=#
function params_constructor_expr(material, name, spec, sim_float)
    body = param_constructor_body(spec, sim_float)
    args = [esc(d.name) for d in spec.decls]
    # with a marker field the type parameters of the models cannot be written down, so the
    # positional call is the fully implicit one, which infers them from the values
    has_markers = any(is_model_param_decl, spec.decls)
    sim_float || return quote
        function $(esc(name))($(esc(:mat))::$(esc(material)),
                              $(esc(:p))::Base.Dict{Base.Symbol,Base.Any})
            $(body...)
            return $(esc(name))($(args...))
        end
    end
    instantiation = Expr(:curly, esc(name), FLOAT_TYPE_PARAM)
    positional = has_markers ? esc(name) : instantiation
    default_instantiation = Expr(:curly, esc(name), :(Peridynamics.default_float_type()))
    return quote
        function $(instantiation)($(esc(:mat))::$(esc(material)),
                                  $(esc(:p))::Base.Dict{Base.Symbol,Base.Any}) where {$(FLOAT_TYPE_PARAM)<:Base.Real}
            $(body...)
            return $(positional)($(args...))
        end
        function $(esc(name))($(esc(:mat))::$(esc(material)),
                              $(esc(:p))::Base.Dict{Base.Symbol,Base.Any})
            return $(default_instantiation)($(esc(:mat)), $(esc(:p)))
        end
    end
end

function params_interface_exprs(material, name, spec, sim_float)
    # a marker field makes the concrete type depend on the models of the material
    # instance: the type parameter of the marker is answered by the model, exactly like
    # `storage_type` resolves the nested states
    has_cm = any(is_cm_param_decl, spec.decls)
    has_dmg = any(is_dmg_param_decl, spec.decls)
    ft = sim_float ? FLOAT_TYPE_PARAM : :(Peridynamics.default_float_type())
    curly_args = Any[]
    sim_float && push!(curly_args, FLOAT_TYPE_PARAM)
    has_cm && push!(curly_args,
                    :(Peridynamics.constitutive_param_type(Peridynamics.get_constitutive_model(mat),
                                                           $(ft))))
    has_dmg && push!(curly_args,
                     :(Peridynamics.damage_param_type(Peridynamics.get_dmgmodel(mat),
                                                      $(ft))))
    answer = isempty(curly_args) ? esc(name) : Expr(:curly, esc(name), curly_args...)
    point_param_type_expr = if sim_float
        quote
            function Peridynamics.point_param_type(mat::$(esc(material)),
                                                   ::Base.Type{$(FLOAT_TYPE_PARAM)}=Peridynamics.default_float_type()) where {$(FLOAT_TYPE_PARAM)}
                return $(answer)
            end
        end
    else
        quote
            function Peridynamics.point_param_type(mat::$(esc(material)),
                                                   ::Base.Type=Peridynamics.default_float_type())
                return $(answer)
            end
        end
    end
    get_point_params_expr = quote
        function Peridynamics.get_point_params(mat::$(esc(material)),
                                               p::Base.Dict{Base.Symbol,Base.Any})
            return $(esc(name))(mat, p)
        end
    end
    # the allowed keywords follow from the declarations, so a new parameter cannot be
    # rejected by `material!` because someone forgot to add it here
    allowed_kwargs_expr = quote
        function Peridynamics.allowed_material_kwargs(::$(esc(material)))
            return $(Expr(:tuple, (QuoteNode(k) for k in spec.kwargs)...))
        end
    end
    return (point_param_type_expr, get_point_params_expr, allowed_kwargs_expr)
end

# --------------------------------------------------------------------------------------
# `@params material PointParameters begin ... end` -- another constructor for a type
# --------------------------------------------------------------------------------------

#=
Several materials share one point parameter type and differ only in how they read it, e.g.
the bond-based materials, which force a Poisson ratio and scale the bond constant. Such a
material declares the parameters again, but the struct is defined only once.
=#
function __params_constructor(material, params, block, mod::Module)
    local _spec = get_param_decls(block.args, mod)
    isempty(_spec.decls) && throw(ArgumentError(empty_params_msg(params)))
    local _sim_float = params_use_sim_float(_spec)
    local _constructor = params_constructor_expr(material, params, _spec, _sim_float)
    local _field_names = Expr(:tuple, (QuoteNode(d.name) for d in _spec.decls)...)
    # a material family shares only the constructor, see `is_material_family`
    local _is_family = is_material_family(material, mod)
    local _interface = _is_family ? () :
                       params_interface_exprs(material, params, _spec, _sim_float)
    local _checks = if _is_family
        quote
            Peridynamics.typecheck_material($(esc(material)))
            Peridynamics.typecheck_param_fields($(esc(params)), $(_field_names))
        end
    else
        quote
            Peridynamics.typecheck_material($(esc(material)))
            Peridynamics.typecheck_params($(esc(material)), $(esc(params)))
            Peridynamics.typecheck_param_fields($(esc(params)), $(_field_names))
        end
    end
    return Expr(:block, _constructor, _interface..., _checks)
end

function typecheck_param_fields(::Type{Param}, names::NTuple{N,Symbol}) where {Param,N}
    fields = fieldnames(Param)
    fields == names && return nothing
    msg = "the declared parameters do not match the fields of `$(Param)`!\n"
    msg *= "  declared: $(join(names, ", "))\n"
    msg *= "  fields:   $(join(fields, ", "))\n"
    msg *= "  A `@params` definition that only adds a constructor to an existing point "
    msg *= "parameter type has to declare exactly its fields, in the same order.\n"
    return throw(ArgumentError(msg))
end

# --------------------------------------------------------------------------------------
# input checks
# --------------------------------------------------------------------------------------

function macrocheck_input_material(material)
    material isa Symbol && return nothing
    (material isa Expr && material.head === :.) && return nothing
    (material isa Expr && material.head === :escape) && return nothing
    (material isa Expr && material.head === :curly) && return nothing
    return throw(ArgumentError("argument `$material` is not a valid material input!\n"))
end

function macrocheck_input_params(params)
    params isa Symbol && return nothing
    (params isa Expr && params.head === :.) && return nothing
    (params isa Expr && params.head === :curly) && return nothing
    msg = "argument `$params` is not a valid point parameter input!\n"
    return throw(ArgumentError(msg))
end

function macrocheck_input_params_block(block)
    (block isa Expr && block.head === :block) && return nothing
    msg = "specified input is not a valid point parameter block expression!\n"
    return throw(ArgumentError(msg))
end

function macrocheck_input_params_struct(params_expr)
    (params_expr isa Expr && params_expr.head === :struct) && return nothing
    msg = "specified input is not a point parameter struct definition!\n"
    msg *= "  Expected `@params struct MyPointParameters ... end`.\n"
    return throw(ArgumentError(msg))
end

function typecheck_material(::Type{Material}) where {Material}
    if !(Material <: AbstractMaterial)
        msg = "$Material is not a valid material type!\n"
        throw(ArgumentError(msg))
    end
    return nothing
end

function typecheck_params(::Type{Material}, ::Type{Param}) where {Material,Param}
    if !(Param <: AbstractPointParameters)
        msg = "$Param is not a subtype of AbstractPointParameters!\n"
        throw(ArgumentError(msg))
    end
    parameters = fieldnames(Param)
    for req_param in required_point_parameters(Material)
        if !in(req_param, parameters)
            msg = "required parameter $req_param not found in $(Param)!\n"
            error(msg)
        end
    end
    return nothing
end

function constructor_check(::Type{Material}, ::Type{Param}) where {Material,Param}
    if !hasmethod(Param, Tuple{Material,Dict{Symbol,Any}})
        throw(InterfaceError(Param, "$(Param)(::$(Material), ::Dict{Symbol,Any})"))
    end
    return nothing
end

"""
    check_model_params(mat)

$(internal_api_warning())

Check that the point parameters of a material have a place for the parameters its models
declare, before `material!` instantiates them: a model with a [`@cm_params`](@ref) /
[`@dmg_params`](@ref) declaration combined with a material whose [`@params`](@ref)
definition lacks the marker field is an error naming the missing marker, and so is a
parameter name that exists in more than one place.
"""
function check_model_params(mat::AbstractMaterial)
    P = point_param_type(mat)
    check_model_marker(mat, get_constitutive_model(mat), :cm, P)
    check_model_marker(mat, get_dmgmodel(mat), :dmg, P)
    check_param_name_collisions(P)
    return nothing
end

function check_model_marker(mat, model, kind::Symbol, ::Type{P}) where {P}
    isnothing(model) && return nothing
    FT = default_float_type()
    mp_type = kind === :cm ? constitutive_param_type(model, FT) :
              damage_param_type(model, FT)
    mp_type === Nothing && return nothing
    has_marker = kind === :cm ? has_cm_param_marker(P) : has_dmg_param_marker(P)
    has_marker && return nothing
    # a hand-written point parameter type may provide the model's parameters itself, as
    # flat fields; what the model needs is that its parameter names are readable
    all(in(fieldnames(P)), fieldnames(mp_type)) && return nothing
    marker = kind === :cm ? "cm_params::ConstitutiveParameters" :
             "dmg_params::DamageParameters"
    what = kind === :cm ? "constitutive model" : "damage model"
    msg = "the $(what) `$(nameof(typeof(model)))` declares point parameters, but the "
    msg *= "point parameters\nof `$(nameof(typeof(mat)))` have no place for them!\n"
    msg *= "  Add the marker field to the `Peridynamics.@params` definition of "
    msg *= "`$(nameof(P))`:\n"
    msg *= "        $(marker)\n"
    return throw(ArgumentError(msg))
end

function check_param_name_collisions(::Type{P}) where {P}
    owners = Dict{Symbol,Vector{String}}()
    for field in fieldnames(P)
        FT = fieldtype(P, field)
        if FT <: Union{AbstractConstitutiveParameters,AbstractDamageParameters}
            owner = FT <: AbstractConstitutiveParameters ? "the constitutive model" :
                    "the damage model"
            for name in fieldnames(FT)
                push!(get!(Vector{String}, owners, name), owner)
            end
        else
            push!(get!(Vector{String}, owners, field), "`$(nameof(P))`")
        end
    end
    for (name, names) in owners
        length(names) > 1 || continue
        msg = "the parameter `$(name)` is declared more than once: by "
        msg *= "$(join(names, " and "))!\n"
        msg *= "  Every parameter needs one owner, so that `params.$(name)` reads "
        msg *= "unambiguously.\n"
        throw(ArgumentError(msg))
    end
    return nothing
end

"""
    StandardParameters

$(extension_api_note())

Parameter block of the parameters a standard peridynamics model needs: the discretization
and the elastic parameters, the bond constant `bc`, and the marker field that holds
whatever parameters the damage model of the material declares — with the standard
[`CriticalStretch`](@ref), the fracture parameters `Gc` and `εc`. Materials that carry a
constitutive model add `cm_params::ConstitutiveParameters` themselves, e.g.
[`RKCPointParameters`](@ref). See [`@params_fields`](@ref),
[`ConstitutiveParameters`](@ref), [`DamageParameters`](@ref).

$(block_table(StandardParameters))
"""
@params_fields StandardParameters begin
    @inherit DiscretizationParameters ElasticParameters
    @derived bc = 18 * K / (π * δ^4)
    dmg_params::DamageParameters
end

"""
    StandardPointParameters

$(internal_api_warning())

Type containing the material parameters for a standard peridynamics model without a
constitutive model of its own, e.g. the bond-based and the ordinary state-based
formulations of peridynamics.

# Fields

- `δ::FT`: Horizon.
- `rho::FT`: Density.
- `E::FT`: Young's modulus.
- `nu::FT`: Poisson's ratio.
- `G::FT`: Shear modulus.
- `K::FT`: Bulk modulus.
- `λ::FT`: 1st Lamé parameter.
- `μ::FT`: 2nd Lamé parameter.
- `bc::FT`: Bond constant.
- `dmg_params::DMP`: Parameters of the damage model — with [`CriticalStretch`](@ref) the
    critical energy release rate `Gc` and the critical stretch `εc`, read flat as
    `params.Gc` and `params.εc`.

$(block_table(StandardPointParameters))
"""
@params struct StandardPointParameters
    @inherit StandardParameters
end

# every material that links `StandardPointParameters` without declaring the parameters again
# reads them like this, e.g. `OSBMaterial` and `RKCRMaterial`
@params AbstractMaterial StandardPointParameters begin
    @inherit StandardParameters
end
