function point_param_type(mat::AbstractMaterial)
    return throw(InterfaceError(mat, "point_param_type", params_macro_hint(mat)))
end

# point parameters that are not generic in their float type, i.e. ones that are not
# generated by `@params`, ignore the requested float type
point_param_type(mat::AbstractMaterial, ::Type) = point_param_type(mat)

function get_point_params(mat::AbstractMaterial, ::Dict{Symbol,Any})
    return throw(InterfaceError(mat, "get_point_params", params_macro_hint(mat)))
end

function required_point_parameters(mat::Type{<:AbstractMaterial})
    return throw(InterfaceError(mat, "required_point_parameters", family_method_hint()))
end

function allowed_material_kwargs(mat::AbstractMaterial)
    return throw(InterfaceError(mat, "allowed_material_kwargs", params_macro_hint(mat)))
end

function params_macro_hint(mat)
    name = mat isa Type ? nameof(mat) : nameof(typeof(mat))
    msg = "Declare the point parameters of `$(name)` with `@params`, e.g.\n"
    msg *= "        Peridynamics.@params $(name) struct MyPointParameters\n"
    msg *= "            @inherit StandardParameters\n"
    msg *= "        end\n"
    msg *= "    which defines `point_param_type`, `get_point_params` and "
    msg *= "`allowed_material_kwargs` for you."
    return msg
end

function family_method_hint()
    msg = "This method is defined for every material family of this package, so a material "
    msg *= "that\n    subtypes a family, e.g. `AbstractBondSystemMaterial{NoCorrection}`, "
    msg *= "inherits it. Define\n    it directly only when introducing a new family."
    return msg
end

"""
    @params material struct PointParameters ... end
    @params material PointParameters

$(extension_api_note())

Declare the point parameters of a material, i.e. the values [`material!`](@ref) assigns to a
point set. The first form defines a new point parameter type and makes it the point
parameters of `material`. The second form makes `material` use the point parameters that
were defined for another material, e.g. `CRMaterial` uses the `CPointParameters` of
`CMaterial`. This is the parameter counterpart of [`@storage`](@ref): one definition per
material, reuse through [`@inherit`](@ref) and the second form.

The macro generates the struct, the constructor that reads the keywords of `material!`, the
converting constructor between float types, `point_param_type`, `get_point_params`,
`allowed_material_kwargs` and the `log_param_property` methods, so that these cannot drift
apart from each other.

# Declaring a parameter

| declaration | meaning |
|:---|:---|
| `rho` | required keyword `rho` |
| `sigma_y = Inf` | keyword `sigma_y`, defaulting to `Inf` |
| `C1 = 30 * μ / (π * δ^4)` | keyword `C1`, defaulting to an expression of the parameters before it |
| `n::Int = 4` | keyword pinned to a concrete type |
| `@kwarg gamma_c gammac = 1e-10` | keyword name differs from the parameter name |
| `@derived bc = 18 * K / (π * δ^4)` | computed, **not** a keyword |
| `@derived (; δ, rho) = get_discretization_params(; horizon, rho)` | a group of parameters computed by one call |
| `@log "shear modulus" G` | also write the parameter to the simulation log |
| `@inherit StandardParameters` | include the declarations of a block or of another point parameter type |
| `dmg_params::DamageParameters` | the place for the parameters of the damage model |

Every right-hand side follows one rule:

| position | meaning |
|:---|:---|
| before `;` | the parameters declared above, `mat`, and anything in scope of the module |
| after `;` | names of `material!` keywords, in shorthand |

This is one rule for a constant default, a value derived from other parameters and a call
that supplies a whole group, and it is why the order of the declarations matters. See
[`@derived`](@ref).

# Types

| declaration | type of the parameter |
|:---|:---|
| `rho` | the float type of the simulation |
| `n::Int` | `Int`, for every simulation |
| `C::SArray{NTuple{4,3},FT,4,81}` | follows the float type of the simulation through `FT` |

Inside a definition, `FT` stands for the float type of the simulation, so a parameter whose
type is built from it stays generic. This is how the correspondence formulation declares its
elastic stiffness tensor:

```julia
@derived C::SArray{NTuple{4,3},FT,4,81} = get_hooke_matrix(nu, λ, μ)
```

The generated struct is parametric in `FT` when any parameter follows it:

```julia
struct BBPointParameters{FT<:Real,DMP} <: AbstractPointParameters
    δ::FT
    rho::FT
    ...
    bc::FT
    dmg_params::DMP
end
```

`Peridynamics.point_param_type(mat)` returns the instantiation with the float type of the
simulation and `Peridynamics.point_param_type(mat, Float32)` the `Float32` one. Point
parameters are `isbits`, which is what lets them be captured by value in a kernel, so an
array-valued parameter is an `SArray`, never an `Array`.

# Reusing parameters with `@inherit`

[`@inherit`](@ref) includes all parameters of a parameter block defined with
[`@params_fields`](@ref) or of the point parameters of another material, with the merge rules
of `@storage`: two `@inherit`s may contribute the same parameter only if they declare it
identically, and a declaration in the body overrides an inherited one in place. This is how
the dual-horizon bond-based material halves the bond constant of the bond-based one:

```julia
Peridynamics.@params DHBBMaterial struct DHBBPointParameters
    @inherit BBPointParameters
    @derived bc = 0.5 * 18 * K / (π * δ^4)
end
```

The package ships the blocks [`DiscretizationParameters`](@ref),
[`ElasticParameters`](@ref), [`BBElasticParameters`](@ref),
[`BondHorizonParameters`](@ref), [`InteractionParameters`](@ref) and
[`StandardParameters`](@ref), each documented with the parameters it exposes. The fracture
parameters belong to the damage model, see [`@dmg_params`](@ref). Names inside the
definition are resolved in the module of the definition first and in `Peridynamics` second,
so they need no import. By convention a block is named `...Parameters` and a point parameter
type `...PointParameters`, as a field block is named `...Fields` and a storage `...Storage`.

# Parameters of the models

A material whose constitutive model or damage model declares parameters of its own with
[`@cm_params`](@ref) / [`@dmg_params`](@ref) gives them a place with a marker field,
`cm_params::ConstitutiveParameters` or `dmg_params::DamageParameters`, exactly like a
storage gives the state of its models a place with `cm_state::ConstitutiveState`. The
model's declarations may read every parameter declared above the marker, and the model
parameters are read flat off the point parameters, e.g. `params.Gc`. See
[`ConstitutiveParameters`](@ref) and [`DamageParameters`](@ref).

# Examples

A material with two parameters of its own on top of the standard ones:

```julia
Peridynamics.@params MyMaterial struct MyPointParameters
    @inherit StandardParameters
    @log "yield stress" sigma_y = Inf
    hardening = 0.0
end
```

`material!(body; horizon, rho, E, nu, Gc, sigma_y=250.0)` then works, `hardening` is
optional, anything else is rejected, and the yield stress appears in the simulation log.

A material that uses the point parameters defined for another one:

```julia
Peridynamics.@params MyOtherMaterial MyPointParameters
```

The generated constructor reads the material as `mat`, so the same type serves every
material it is used for. Only point parameters defined with `@params` can be shared this
way. A hand-written subtype of `AbstractPointParameters` defines `point_param_type`,
`get_point_params` and `allowed_material_kwargs` itself.

See also [`@params_fields`](@ref), [`@inherit`](@ref), [`@derived`](@ref),
[`@cm_params`](@ref), [`@dmg_params`](@ref), [`@storage`](@ref).
"""
macro params(args...)
    length(args) == 2 || throw(ArgumentError(params_forms_msg()))
    material, params = args
    macrocheck_input_material(material)
    if params isa Expr && params.head === :struct
        return __params_struct(material, params, __module__)
    end
    macrocheck_input_params(params)
    return __params_link(material, params, __module__)
end

function params_forms_msg()
    msg = "`@params` expects a material and either a `struct` definition or the name of "
    msg *= "point parameters defined for another material!\n"
    msg *= "        Peridynamics.@params MyMaterial struct MyPointParameters\n"
    msg *= "            @inherit StandardParameters\n"
    msg *= "        end\n"
    msg *= "        Peridynamics.@params MyOtherMaterial MyPointParameters\n"
    return msg
end

# --------------------------------------------------------------------------------------
# `@params material struct PointParameters ... end`: define everything
# --------------------------------------------------------------------------------------

function __params_struct(material, params_expr, mod::Module)
    local _name, _supertype = get_params_header(params_expr)
    local _spec = get_param_decls(params_expr.args[3].args, mod)
    isempty(_spec.decls) && throw(ArgumentError(empty_params_msg(_name)))
    local _sim_float = params_use_sim_float(_spec)

    local _struct = params_struct_expr(params_expr, _name, _supertype, _spec, _sim_float)
    local _convert = params_convert_expr(_name, _spec, _sim_float)
    local _fields_expr = quote
        function Peridynamics.param_fields_expr(::Base.Type{<:$(esc(_name))})
            return $(QuoteNode(_spec))
        end
    end
    local _logs = param_log_methods(_spec, _name)
    local _markers = params_marker_exprs(_name, _spec)
    # the docstring is attached last, so that a `$(block_table(Name))` in it can already read
    # the declarations that were just registered
    local _doc = quote
        Base.@__doc__ $(esc(_name))
    end
    local _constructor = params_constructor_expr(_name, _spec, _sim_float)
    local _interface = params_interface_exprs(material, esc(_name), _spec, _sim_float)
    # emitted last, so that `@test_throws` sees the errors of the declarations first
    local _checks = quote
        Peridynamics.typecheck_material($(esc(material)))
        Peridynamics.typecheck_params($(esc(material)), $(esc(_name)))
    end
    return Expr(:block, _struct, _convert, _fields_expr, _logs..., _markers..., _doc,
                _constructor, _interface..., _checks)
end

function get_params_header(params_expr)
    header = params_expr.args[2]
    if header isa Symbol
        # case `struct MyPointParameters`
        return header, :(Peridynamics.AbstractPointParameters)
    elseif header isa Expr && header.head === :(<:) && header.args[1] isa Symbol
        # case `struct MyPointParameters <: AbstractPointParameters`
        return header.args[1], header.args[2]
    end
    return throw(ArgumentError(params_header_msg(header)))
end

function params_header_msg(header)
    is_parametric = header isa Expr &&
                    (header.head === :curly ||
                     (header.head === :(<:) && header.args[1] isa Expr &&
                      header.args[1].head === :curly))
    is_parametric || return "point parameter header `$(header)` not supported!\n"
    msg = "point parameters cannot declare their own type parameters, got `$(header)`!\n"
    msg *= "  `@params` derives the type parameters from the declarations, so that the "
    msg *= "point parameters are generic in the float type of the simulation. Declare them "
    msg *= "without type parameters, and give a parameter a concrete type only to pin it, "
    msg *= "e.g.\n"
    msg *= "        n_substeps::Int\n"
    return msg
end

function empty_params_msg(name)
    msg = "the point parameters `$(name)` declare no parameter at all!\n"
    msg *= "  Inherit the parameters of the material family, e.g. `@inherit "
    msg *= "StandardParameters`.\n"
    return msg
end

#=
The generated constructor is the constructor that used to be written by hand, so nothing
about the values it computes or the order in which it computes them changes. It accepts any
material, because the point parameters of one material may be used for another one with the
second form of `@params`. The declarations read the material as `mat`. `mat` and `p` are
escaped, because the default and provider expressions of the declarations are escaped and
have to see them.
=#
function params_constructor_expr(name, spec, sim_float)
    body = param_constructor_body(spec, sim_float)
    args = [esc(d.name) for d in spec.decls]
    signature_args = (:($(esc(:mat))::Peridynamics.AbstractMaterial),
                      :($(esc(:p))::Base.Dict{Base.Symbol,Base.Any}))
    # with a marker field the type parameters of the models cannot be written down, so the
    # positional call is the fully implicit one, which infers them from the values
    has_markers = any(is_model_param_decl, spec.decls)
    sim_float || return quote
        function $(esc(name))($(signature_args...))
            $(body...)
            return $(esc(name))($(args...))
        end
    end
    instantiation = Expr(:curly, esc(name), FLOAT_TYPE_PARAM)
    positional = has_markers ? esc(name) : instantiation
    default_instantiation = Expr(:curly, esc(name), :(Peridynamics.default_float_type()))
    return quote
        function $(instantiation)($(signature_args...)) where {$(FLOAT_TYPE_PARAM)<:Base.Real}
            $(body...)
            return $(positional)($(args...))
        end
        function $(esc(name))($(signature_args...))
            return $(default_instantiation)($(esc(:mat)), $(esc(:p)))
        end
    end
end

#=
`type_expr` is what the generated methods name the point parameter type with: the escaped
name for a definition, the resolved type itself for the second form of `@params`.
=#
function params_interface_exprs(material, type_expr, spec, sim_float)
    # a marker field makes the concrete type depend on the models of the material
    # instance: the type parameter of the marker is answered by the model, exactly like
    # `storage_type` resolves the nested states
    has_cm = any(is_cm_param_decl, spec.decls)
    has_dmg = any(is_dmg_param_decl, spec.decls)
    ft = sim_float ? FLOAT_TYPE_PARAM : :(Peridynamics.default_float_type())
    curly_args = Any[]
    sim_float && push!(curly_args, FLOAT_TYPE_PARAM)
    has_cm && push!(curly_args,
                    :(Peridynamics.constitutive_param_type(Peridynamics.get_constitutive_model(mat),
                                                           $(ft))))
    has_dmg && push!(curly_args,
                     :(Peridynamics.damage_param_type(Peridynamics.get_dmgmodel(mat),
                                                      $(ft))))
    answer = isempty(curly_args) ? type_expr : Expr(:curly, type_expr, curly_args...)
    point_param_type_expr = if sim_float
        quote
            function Peridynamics.point_param_type(mat::$(esc(material)),
                                                   ::Base.Type{$(FLOAT_TYPE_PARAM)}=Peridynamics.default_float_type()) where {$(FLOAT_TYPE_PARAM)}
                return $(answer)
            end
        end
    else
        quote
            function Peridynamics.point_param_type(mat::$(esc(material)),
                                                   ::Base.Type=Peridynamics.default_float_type())
                return $(answer)
            end
        end
    end
    get_point_params_expr = quote
        function Peridynamics.get_point_params(mat::$(esc(material)),
                                               p::Base.Dict{Base.Symbol,Base.Any})
            return $(type_expr)(mat, p)
        end
    end
    # the allowed keywords follow from the declarations, so a new parameter cannot be
    # rejected by `material!` because someone forgot to add it here
    allowed_kwargs_expr = quote
        function Peridynamics.allowed_material_kwargs(::$(esc(material)))
            return $(Expr(:tuple, (QuoteNode(k) for k in spec.kwargs)...))
        end
    end
    return (point_param_type_expr, get_point_params_expr, allowed_kwargs_expr)
end

# --------------------------------------------------------------------------------------
# `@params material PointParameters`: use the point parameters of another material
# --------------------------------------------------------------------------------------

#=
The declarations of the type are the ones its definition registered, so the interface of the
second material is generated from exactly the same table as the one of the first, and it is
resolved while the macro is expanded, the way `@inherit` resolves a block.
=#
function __params_link(material, params, mod::Module)
    local _type = resolve_in_mod_or_peridynamics(mod, params)
    isnothing(_type) && throw(ArgumentError(unresolved_params_msg(params, mod)))
    if !(_type isa Type && _type <: AbstractPointParameters)
        throw(ArgumentError(not_point_params_msg(params)))
    end
    local _spec = registered_param_fields(_type)
    isnothing(_spec) && throw(ArgumentError(handwritten_params_msg(params)))
    local _sim_float = params_use_sim_float(_spec)
    local _interface = params_interface_exprs(material, _type, _spec, _sim_float)
    local _checks = quote
        Peridynamics.typecheck_material($(esc(material)))
        Peridynamics.typecheck_params($(esc(material)), $(_type))
    end
    return Expr(:block, _interface..., _checks)
end

# `invokelatest` because the method of `param_fields_expr` for the type was defined by a
# top-level statement that is newer than this macro
function registered_param_fields(::Type{P}) where {P}
    return try
        Base.invokelatest(param_fields_expr, P)
    catch e
        e isa ArgumentError || rethrow()
        nothing
    end
end

function unresolved_params_msg(params, mod::Module)
    msg = "cannot resolve the point parameters `$(params)`!\n"
    msg *= "  They have to be defined by an earlier top-level statement and be resolvable "
    msg *= "in `$(mod)` or in `Peridynamics`.\n"
    return msg
end

function not_point_params_msg(params)
    msg = "`$(params)` is not a point parameter type!\n"
    msg *= "  The second argument of `@params` is the name of point parameters defined "
    msg *= "with `@params` for another material, or a `struct` definition.\n"
    return msg
end

function handwritten_params_msg(params)
    msg = "`$(params)` was not defined with `@params`, so it cannot be used for another "
    msg *= "material!\n"
    msg *= "  A hand-written point parameter type defines `point_param_type`, "
    msg *= "`get_point_params` and\n  `allowed_material_kwargs` itself, or is replaced by "
    msg *= "a `@params` definition.\n"
    return msg
end

# --------------------------------------------------------------------------------------
# input checks
# --------------------------------------------------------------------------------------

function macrocheck_input_material(material)
    material isa Symbol && return nothing
    (material isa Expr && material.head === :.) && return nothing
    (material isa Expr && material.head === :escape) && return nothing
    (material isa Expr && material.head === :curly) && return nothing
    return throw(ArgumentError("argument `$material` is not a valid material input!\n"))
end

function macrocheck_input_params(params)
    params isa Symbol && return nothing
    (params isa Expr && params.head === :.) && return nothing
    return throw(ArgumentError(params_forms_msg()))
end

function typecheck_material(::Type{Material}) where {Material}
    if !(Material <: AbstractMaterial)
        msg = "$Material is not a valid material type!\n"
        throw(ArgumentError(msg))
    end
    return nothing
end

function typecheck_params(::Type{Material}, ::Type{Param}) where {Material,Param}
    if !(Param <: AbstractPointParameters)
        msg = "$Param is not a subtype of AbstractPointParameters!\n"
        throw(ArgumentError(msg))
    end
    parameters = fieldnames(Param)
    for req_param in required_point_parameters(Material)
        if !in(req_param, parameters)
            msg = "required parameter $req_param not found in $(Param)!\n"
            error(msg)
        end
    end
    return nothing
end

"""
    check_model_params(mat)

$(internal_api_warning())

Check that the point parameters of a material have a place for the parameters its models
declare, before `material!` instantiates them: a model with a [`@cm_params`](@ref) /
[`@dmg_params`](@ref) declaration combined with a material whose [`@params`](@ref)
definition lacks the marker field is an error naming the missing marker, and so is a
parameter name that exists in more than one place.
"""
function check_model_params(mat::AbstractMaterial)
    P = point_param_type(mat)
    check_model_marker(mat, get_constitutive_model(mat), :cm, P)
    check_model_marker(mat, get_dmgmodel(mat), :dmg, P)
    check_param_name_collisions(P)
    return nothing
end

function check_model_marker(mat, model, kind::Symbol, ::Type{P}) where {P}
    isnothing(model) && return nothing
    FT = default_float_type()
    mp_type = kind === :cm ? constitutive_param_type(model, FT) :
              damage_param_type(model, FT)
    mp_type === Nothing && return nothing
    has_marker = kind === :cm ? has_cm_param_marker(P) : has_dmg_param_marker(P)
    has_marker && return nothing
    # a hand-written point parameter type may provide the model's parameters itself, as
    # flat fields; what the model needs is that its parameter names are readable
    all(in(fieldnames(P)), fieldnames(mp_type)) && return nothing
    marker = kind === :cm ? "cm_params::ConstitutiveParameters" :
             "dmg_params::DamageParameters"
    what = kind === :cm ? "constitutive model" : "damage model"
    msg = "the $(what) `$(nameof(typeof(model)))` declares point parameters, but the "
    msg *= "point parameters\nof `$(nameof(typeof(mat)))` have no place for them!\n"
    msg *= "  Add the marker field to the `Peridynamics.@params` definition of "
    msg *= "`$(nameof(P))`:\n"
    msg *= "        $(marker)\n"
    return throw(ArgumentError(msg))
end

function check_param_name_collisions(::Type{P}) where {P}
    owners = Dict{Symbol,Vector{String}}()
    for field in fieldnames(P)
        FT = fieldtype(P, field)
        if FT <: Union{AbstractConstitutiveParameters,AbstractDamageParameters}
            owner = FT <: AbstractConstitutiveParameters ? "the constitutive model" :
                    "the damage model"
            for name in fieldnames(FT)
                push!(get!(Vector{String}, owners, name), owner)
            end
        else
            push!(get!(Vector{String}, owners, field), "`$(nameof(P))`")
        end
    end
    for (name, names) in owners
        length(names) > 1 || continue
        msg = "the parameter `$(name)` is declared more than once: by "
        msg *= "$(join(names, " and "))!\n"
        msg *= "  Every parameter needs one owner, so that `params.$(name)` reads "
        msg *= "unambiguously.\n"
        throw(ArgumentError(msg))
    end
    return nothing
end

"""
    StandardParameters

$(extension_api_note())

Parameter block of the parameters a standard peridynamics model needs: the discretization
and the elastic parameters, the bond constant `bc`, and the marker field that holds
whatever parameters the damage model of the material declares. With the standard
[`CriticalStretch`](@ref) these are the fracture parameters `Gc` and `εc`. Materials that carry a
constitutive model add `cm_params::ConstitutiveParameters` themselves, e.g.
[`RKCPointParameters`](@ref). See [`@params_fields`](@ref),
[`ConstitutiveParameters`](@ref), [`DamageParameters`](@ref).

$(block_table(StandardParameters))
"""
@params_fields StandardParameters begin
    @inherit DiscretizationParameters ElasticParameters
    @derived bc = 18 * K / (π * δ^4)
    dmg_params::DamageParameters
end
