"""
    force_density_point!(storage, system, mat, paramsetup, t, Δt, i)

$(extension_api_note())

Calculate the internal force density of point `i` and accumulate it into
`storage.b_int`. This is the one method a material has to define, everything else about a
material is declared with [`@params`](@ref) and [`@storage`](@ref).

It is called once per local point and per time step, from inside a loop over
[`each_point_idx`](@ref) that runs on every thread and on every MPI rank. A method must
therefore only ever write to the columns of point `i` and read every other point through
the system, which is what makes the same material run under multithreading and MPI without
a change.

# Arguments

- `storage`: The storage of the body chunk, holding every field of the simulation.
- `system`: The system of the body chunk, e.g. a [`BondSystem`](@ref). Dispatch on it to say
    which discretization the material is written for.
- `mat`: The material.
- `paramsetup`: The parameter setup of the body chunk, one set of point parameters or a
    handler for a body where [`material!`](@ref) was called more than once.
    `get_params(paramsetup, i)` resolves the set of point `i` once at the top, and a material
    that averages a parameter across a bond reads the set of the neighbor with
    `get_params(paramsetup, j)` inside the loop, see [`get_params`](@ref).
- `t::Real`: The current simulation time.
- `Δt::Real`: The current time step.
- `i::Int`: The index of the local point that is evaluated.

# Default

A `MethodError`, because there is nothing sensible a material could inherit here.

# Example

The force density of a bond-based material. The bonds that failed were deactivated by
[`calc_failure!`](@ref) right before, so a material only multiplies
[`bond_is_active`](@ref) in. The current length of the bond comes from
[`current_bond_length`](@ref) and never from gathering the two positions and taking the
norm.

```julia
function Peridynamics.force_density_point!(storage, system::Peridynamics.BondSystem,
                                           mat::MyMaterial, paramsetup, t, Δt, i)
    (; volume) = system
    params = Peridynamics.get_params(paramsetup, i)
    for bond_id in Peridynamics.each_bond_idx(system, i)
        j = Peridynamics.get_neighbor(system, bond_id)
        L = Peridynamics.reference_bond_length(system, bond_id)
        Δxij = Peridynamics.get_vector_diff(storage.position, i, j,
                                            Peridynamics.dims(system))
        l = Peridynamics.current_bond_length(storage, system, i, bond_id)
        ε = (l - L) / L
        ω = Peridynamics.bond_is_active(storage, system, bond_id) *
            Peridynamics.surface_correction_factor(system, bond_id)
        b = ω * params.bc * ε * volume[j] / l .* Δxij
        Peridynamics.update_add_vector!(storage.b_int, i, b, Peridynamics.dims(system))
    end
    return nothing
end
```

A kernel that needs the stretch and not the length takes [`bond_stretch`](@ref) instead.

See also [`storage_type`](@ref), [`get_params`](@ref), [`each_bond_idx`](@ref),
[`current_bond_length`](@ref), [`bond_stretch`](@ref), [`@storage`](@ref).
"""
function force_density_point! end

"""
    storage_type(mat)
    storage_type(mat, ::Type{FT})
    storage_type(mat, ::Type{FT}, ::Val{N})

$(extension_api_note())

Return the storage type of a material, instantiated for the float type `FT` and the number
of spatial dimensions `N` of the simulation. The returned instantiation holds the arrays of
the CPU. `N` is the leading type parameter of the generated storage and is what
[`get_n_dim`](@ref) reads off it. It defaults to `3`, and the storage of a body chunk gets
it from the system of the chunk, so a storage can never disagree with its system.

# Default

An [`InterfaceError`](@ref) that asks for a [`@storage`](@ref) declaration, which generates
this method.

See also [`@storage`](@ref), [`init_field`](@ref), [`get_n_dim`](@ref).
"""
function storage_type(mat::AbstractMaterial)
    return throw(InterfaceError(mat, "storage_type", storage_macro_hint(mat)))
end

function storage_macro_hint(mat)
    name = mat isa Type ? nameof(mat) : nameof(typeof(mat))
    msg = "Declare the storage of `$(name)` with `@storage`, e.g.\n"
    msg *= "        Peridynamics.@storage $(name) struct MyStorage\n"
    msg *= "            @inherit VelocityVerletFields\n"
    msg *= "            my_field::PointScalar\n"
    msg *= "            dmg_state::DamageState\n"
    msg *= "        end\n"
    msg *= "    which defines `storage_type` and `get_storage` for you."
    return msg
end

# a storage that is not generic in its float type or its dimension, i.e. one that is not
# generated by `@storage`, ignores both
storage_type(mat::AbstractMaterial, ::Type) = storage_type(mat)
storage_type(mat::AbstractMaterial, ::Type, ::Val) = storage_type(mat)

function get_storage(material, solver, system)
    return throw(InterfaceError(material, "get_storage", storage_macro_hint(material)))
end

"""
    init_field(material, solver, system, ::Val{field})

$(extension_api_note())

Return the initial value of a storage field. Every field of a storage generated by
[`@storage`](@ref) is allocated by this function, in this order:

1. the system, which owns `position` and every field whose initial value is system
   knowledge, e.g. the neighbor count that `n_active_bonds` starts with,
2. the field shape of a field declared with [`@lth`](@ref) or [`@htl`](@ref), because
   whether a field has halo entries is storage knowledge that a time solver cannot have,
3. the time solver, which says whether it needs the field and at which extent,
4. the field shape of every other declared field,
5. an `InterfaceError` that asks for an `init_field` method.

A method of this function for a specific material is more specific than the fallback above
and therefore wins, which is the escape hatch for a field that no field shape describes and
for a shaped field that has to be filled by hand.

# Default

The five steps above, ending in an [`InterfaceError`](@ref) when no step answers.

# Example

```julia
function Peridynamics.init_field(::MyMaterial, ::Peridynamics.AbstractTimeSolver,
                                 system::Peridynamics.AbstractSystem, ::Val{:my_field})
    return zeros(Peridynamics.get_n_points(system))
end
```

See also [`@storage`](@ref), [`storage_type`](@ref).
"""
function init_field(material, solver, system, field)
    Storage = storage_type(material, float_type(system), dims(system))
    field_value_system = init_field_system(system, field)
    isnothing(field_value_system) || return field_value_system
    field_value_halo = init_field_storage(Storage, system, field, HaloPoints())
    isnothing(field_value_halo) || return field_value_halo
    field_value_solver = resolve_solver_field(init_field_solver(solver, system, field),
                                              Storage, system, field)
    isnothing(field_value_solver) || return field_value_solver
    field_value_storage = init_field_storage(Storage, system, field, LocalPoints())
    isnothing(field_value_storage) || return field_value_storage
    method_msg = "init_field(::$(typeof(material)), "
    method_msg *= "::$(typeof(solver)), "
    method_msg *= "::$(typeof(system)), "
    method_msg *= "::$(typeof(field)))"
    return throw(InterfaceError(material, method_msg, init_field_hint(field)))
end

#=
A time solver answers `init_field_solver` either with one of the markers of
`core/storage_fields.jl`, which is how every solver of this package does it, or with the
field itself, which is how a third party solver allocates a field that no field shape
describes. Anything that is not a marker is passed through unchanged, including the
`nothing` of a solver that has nothing to say about the field.
=#
@inline resolve_solver_field(field_value, Storage, system, field) = field_value

@inline function resolve_solver_field(::EmptyField, Storage, system, field)
    return alloc_empty_field(Storage, field)
end

@inline function resolve_solver_field(marker::FullField, Storage, system, field)
    field_value = init_field_storage(Storage, system, field, marker)
    isnothing(field_value) && throw(ArgumentError(unshaped_field_msg(Storage, field)))
    return field_value
end

function unshaped_field_msg(::Type{S}, ::Val{Field}) where {S,Field}
    msg = "the time solver needs the storage field `$(Field)`, but `$(nameof(S))` declares "
    msg *= "it with a container type!\n"
    msg *= "  Only a field declared with a field shape can be sized by a time solver. "
    msg *= "Declare it with the shape it has, e.g.\n"
    msg *= "        $(Field)::PointVector\n"
    msg *= "    or inherit it from the field block of the time solver, e.g.\n"
    msg *= "        @inherit VelocityVerletFields\n"
    msg *= "    or define an `init_field` method that allocates it.\n"
    return msg
end

"""
    init_field_storage(::Type{Storage}, system, field, extent)

$(internal_api_warning())

Return the value of `field` as it follows from the field shape it was declared with in the
[`@storage`](@ref) definition of `Storage`, or `nothing` if the field was declared with a
plain container type or does not have the requested `extent`. Methods of this function are
generated by `@storage`, so a field declared with a field shape never needs an
[`init_field`](@ref) method.
"""
@inline function init_field_storage(::Type, system, field, extent)
    return nothing
end

function init_field_hint(::Val{Field}) where {Field}
    msg = "Either declare `$(Field)` with a field shape in the `@storage` definition, "
    msg *= "e.g.\n"
    msg *= "        $(Field)::PointScalar\n"
    msg *= "    or inherit it from the storage of the material family, e.g.\n"
    msg *= "        @inherit RKCStorage\n"
    msg *= "    or define the `init_field` method shown above."
    return msg
end

init_field_hint(field) = ""

"""
    @storage material storage
    @storage material solver storage

$(extension_api_note())

A macro for automatic creation of a storage type. The macro then maps a specified `material`
type with the `storage` structure. When no solver is specified, this storage is always used
independently of the solver type. Specifying a solver allows the usage of customized
storages for a solver.

# Declaring a field

A field is declared with a **field shape**, which says what the field *is*. The shape
determines the container type, the element type and the allocation, so a field declared with
a shape needs no [`init_field`](@ref) method:

| shape | container | rows | entries |
|:---|:---|:---|:---|
| [`PointScalar`](@ref) | `Vector` | – | points |
| [`PointVector`](@ref) | `Matrix` | `get_n_dim(system)` | points |
| [`PointTensor`](@ref) | `Matrix` | `get_n_dim(system)^2` | points |
| [`PointSymTensor`](@ref) | `Matrix` | `d * (d + 1) ÷ 2` | points |
| [`PointField{N}`](@ref PointField) | `Matrix` | `N` | points |
| [`BondScalar`](@ref) | `Vector` | – | bonds |
| [`BondVector`](@ref) | `Matrix` | `get_n_dim(system)` | bonds |
| [`BondTensor`](@ref) | `Matrix` | `get_n_dim(system)^2` | bonds |
| [`BondSymTensor`](@ref) | `Matrix` | `d * (d + 1) ÷ 2` | bonds |
| [`BondField{N}`](@ref BondField) | `Matrix` | `N` | bonds |
| [`DofVector`](@ref) | `Vector` | – | degrees of freedom |

A **point shape makes the field point data**, which is what can be exported to VTK files. A
bond or dof shape is not point data.

## Element type

A shape written without an element type follows the float type of the simulation, see
[`SimFloat`](@ref). A shape with an element type pins it for every simulation, which is why
`position` is declared `PointVector{Float64}`. `PointScalar{Bool}` and `PointScalar{Int}`
are the non-float cases.

## Annotations

Only the halo exchange is annotated, everything else follows from the shape. Both
annotations give the field one entry per local *and* halo point:

- `@lth`: local-to-halo exchange during the simulation, i.e. the halo entries are updated
    from the chunk that owns the points.
- `@htl`: halo-to-local exchange, i.e. the halo entries are added to the local entries of
    the owning chunk.
- `@inherit`: includes all fields of one or more other storages or of field blocks defined
    with [`@storage_fields`](@ref). See [`@inherit`](@ref) for the merge rules.

## Initial value

The initial value of a shaped field is written `= value`:

| written | result |
|:---|:---|
| omitted | zeros |
| a `Number`, e.g. `= 1.0` or `= true` | every entry that value |
| a `LinearAlgebra.UniformScaling`, e.g. `= I` or `= 2I` | every column that tensor |

A `UniformScaling` requires a shape whose rows are the entries of a square tensor, e.g.
`PointTensor`.

## Anything a shape does not describe

A field can also be declared with a plain container type, e.g.
`zem_stiffness::MArray{NTuple{4,3},Float64,4,81}`. Such a field is not point data and it
needs an [`init_field`](@ref) method that allocates it. A container type that is an `Array`,
e.g. `Vector{Float64}`, still takes part in the type parameters described below, everything
else keeps the type it is declared with.

A field that a time solver works with is the one case where a container type is not enough,
because a solver says only whether it needs the field and at which extent. Inheriting the
field block of the solver, e.g. `@inherit VelocityVerletFields`, declares all of them with
the right shape.

An `init_field` method is also the escape hatch for a *shaped* field: it is more specific
than the generic fallback and therefore wins, so a field can keep its shape, and with it
its type, its size and its export status, while being filled by hand:

````julia
function Peridynamics.init_field(::MyMaterial, ::Peridynamics.AbstractTimeSolver,
                                 system::Peridynamics.AbstractSystem, ::Val{:my_field})
    return ...
end
````

# The generated type

The generated struct must not declare type parameters of its own, because the macro derives
them from the declarations: a leading `N` for the number of spatial dimensions, then `FT`
for the float type of the simulation, then one parameter per distinct combination of element
type and number of array dimensions, and finally one unbounded parameter per nested state
(`cm_state`, `dmg_state`) that the storage declares. The storage of the bond-based material
below becomes

````julia
struct BBStorage{N,FT<:Real,M_F64<:AbstractMatrix{Float64},M_FT<:AbstractMatrix{FT},
                 V_FT<:AbstractVector{FT},DMS} <: AbstractStorage
    position::M_F64
    displacement::M_FT
    ...
    dmg_state::DMS
end
````

so `storage_type(mat)` returns the instantiation with the arrays of the CPU,
`storage_type(mat, Float32)` the one with `Float32` arrays,
`storage_type(mat, Float64, Val(2))` the two-dimensional one, and
`Adapt.adapt(backend, s)` moves a whole storage to another array backend. `N` is what [`get_n_dim`](@ref) reads off a storage, and with it
[`dims`](@ref) works on a storage exactly as it does on a system. Dispatch on the storage
therefore has to be written `::Type{<:BBStorage}` instead of `::Type{BBStorage}`, while
`::BBStorage` is unchanged.

# Example
Example definition of the storage for the bond-based material:
````julia
@storage BBMaterial struct BBStorage <: AbstractStorage
    @inherit VelocityVerletFields DynamicRelaxationFields NewtonKrylovFields
    @inherit BondLengthCache
    strain_energy_density::PointScalar
    dmg_state::DamageState
end
````

The fracture bookkeeping (`damage`, `n_active_bonds`, `bond_active`) is not declared here:
it lives in the state of the damage model, which the `dmg_state::DamageState` field
carries, see [`DamageState`](@ref) and [`@dmg_storage`](@ref). The storage still reads flat,
`storage.bond_active` reaches into the state.
"""
macro storage end

macro storage(material, storage)
    macrocheck_input_material(material)
    macrocheck_input_storage_struct(storage)
    return __storage(material, storage, __module__)
end

macro storage(material, solver, storage)
    macrocheck_input_material(material)
    macrocheck_input_timesolver(solver)
    macrocheck_input_storage_struct(storage)
    return __storage(material, storage, __module__, solver)
end

function __storage(material, storage, mod::Module, timesolver=AbstractTimeSolver)
    local _storage_struct_data = get_storage_structdef(storage, mod)
    local _storage_struct = _storage_struct_data.storage_struct
    local _storage_type = _storage_struct_data.storage_type
    local _decls = _storage_struct_data.decls
    local _params = _storage_struct_data.params
    local _field_params = _storage_struct_data.field_params
    local _uses_sim_float = _storage_struct_data.uses_sim_float
    local _cm_state_field = _storage_struct_data.cm_state_field
    local _dmg_state_field = _storage_struct_data.dmg_state_field

    local _point_field_names = Tuple(QuoteNode(d.name) for d in _decls if is_point_decl(d))
    local _htl_field_names = Tuple(QuoteNode(d.name)
                                   for d in _decls if d.annotation === :htl)
    local _lth_field_names = Tuple(QuoteNode(d.name)
                                   for d in _decls if d.annotation === :lth)
    local _halo_field_names = (_htl_field_names..., _lth_field_names...)

    # one literal `Val` per field instead of one built from a runtime `Symbol`, so that
    # every `init_field` call is resolved at compile time and the whole construction of a
    # storage is type stable
    local _init_field_calls = [
        if is_cm_state_decl(_decl)
            # the state of the constitutive model is not a field of the storage in the sense
            # of `init_field`: it is allocated by the model, not by the system or the solver
            :(Peridynamics.init_constitutive_state(mat, solver, system))
        elseif is_dmg_state_decl(_decl)
            # the same for the state of the damage model
            :(Peridynamics.init_damage_state(mat, solver, system))
        else
            :(Peridynamics.init_field(mat, solver, system,
                                      Base.Val($(QuoteNode(_decl.name)))))
        end
        for _decl in _decls
    ]

    local _dim_constructor = storage_dim_constructor_expr(_storage_type, _decls, _params,
                                                          _uses_sim_float, _field_params,
                                                          _cm_state_field, _dmg_state_field)

    local _get_n_dim = get_n_dim_expr(_storage_type)

    # the storage takes its dimension from the system it is built for, so the two can never
    # disagree
    local _constructor = quote
        function $(esc(_storage_type))(mat::$(esc(material)), solver::$(esc(timesolver)),
                                       system::Peridynamics.AbstractSystem)
            return $(esc(_storage_type)){Peridynamics.get_n_dim(system)}($(_init_field_calls...))
        end
    end

    local _storage_type_function = storage_type_function(material, _storage_type, _params,
                                                         _uses_sim_float, _cm_state_field,
                                                         _dmg_state_field)

    local _constitutive_state = if isnothing(_cm_state_field)
        Expr(:block)
    else
        quote
            @inline function Peridynamics.constitutive_state(s::$(esc(_storage_type)))
                return Base.getfield(s, $(QuoteNode(_cm_state_field)))
            end
            function Peridynamics.has_constitutive_state(::Base.Type{<:$(esc(_storage_type))})
                return true
            end
        end
    end

    local _damage_state = if isnothing(_dmg_state_field)
        Expr(:block)
    else
        quote
            @inline function Peridynamics.damage_state(s::$(esc(_storage_type)))
                return Base.getfield(s, $(QuoteNode(_dmg_state_field)))
            end
            function Peridynamics.has_damage_state(::Base.Type{<:$(esc(_storage_type))})
                return true
            end
        end
    end

    #=
    Moving a storage to another array backend is a matter of moving every field, because the
    struct is parametric in the array type of each of them and its outer constructor
    re-infers the parameters. A storage without a derived type parameter has nothing that
    could be moved, and rebuilding it would convert the adapted fields back, so it gets no
    method.
    =#
    local _adapt_args = [
        :(Adapt.adapt(to, Base.getfield(s, $(QuoteNode(_decl.name))))) for _decl in _decls
    ]
    local _adapt_structure = if isempty(_params)
        Expr(:block)
    else
        quote
            function Adapt.adapt_structure(to, s::$(esc(_storage_type)){N}) where {N}
                return $(esc(_storage_type)){N}($(_adapt_args...))
            end
        end
    end

    local _get_storage = quote
        function Peridynamics.get_storage(mat::$(esc(material)), solver::$(esc(timesolver)),
                                          system::Peridynamics.AbstractSystem)
            return $(esc(_storage_type))(mat, solver, system)
        end
    end

    local _point_data_fields = [
        quote
            function Peridynamics.point_data_field(s::$(esc(_storage_type)),
                                                   ::Val{$(_field)})
                return Base.getfield(s, $(_field))
            end
        end
        for _field in _point_field_names
    ]

    # a storage that carries a damage state also serves the point data the state declares,
    # e.g. the `damage` of the fracture bookkeeping, so the flat tuple is composed with the
    # point data of the concrete state type and unknown `Val`s are forwarded into the state
    local _get_all_point_data_fields = if isnothing(_dmg_state_field)
        quote
            function Peridynamics.point_data_fields(::Base.Type{<:$(esc(_storage_type))})
                return $(Expr(:tuple, _point_field_names...))
            end
        end
    else
        quote
            function Peridynamics.point_data_fields(::Base.Type{S}) where {S<:$(esc(_storage_type))}
                return ($(Expr(:tuple, _point_field_names...))...,
                        Peridynamics.nested_point_data_fields(Base.fieldtype(S, $(QuoteNode(_dmg_state_field))))...)
            end
            function Peridynamics.point_data_field(s::$(esc(_storage_type)), v::Base.Val)
                return Peridynamics.point_data_field(Peridynamics.damage_state(s), v)
            end
        end
    end

    local _halo_to_loc_fields = quote
        function Peridynamics.halo_to_loc_fields(::$(esc(_storage_type)))
            return $(Expr(:tuple, _htl_field_names...))
        end
    end

    local _loc_to_halo_fields = quote
        function Peridynamics.loc_to_halo_fields(::$(esc(_storage_type)))
            return $(Expr(:tuple, _lth_field_names...))
        end
    end

    local _is_halo_fields = [
        quote
            function Peridynamics.is_halo_field(::$(esc(_storage_type)), ::Val{$(_field)})
                return true
            end
        end
        for _field in _halo_field_names
    ]

    local _storage_fields_expr = quote
        function Peridynamics.storage_fields_expr(::Base.Type{<:$(esc(_storage_type))})
            return $(QuoteNode(_decls))
        end
    end

    local _init_field_storages = [
        quote
            function Peridynamics.init_field_storage(::Base.Type{<:$(esc(_storage_type))},
                                                     system::Peridynamics.AbstractSystem,
                                                     ::Val{$(QuoteNode(_decl.name))},
                                                     extent::$(typeof(field_extent(_decl))))
                return $(init_field_storage_call(_decl))
            end
            function Peridynamics.init_field_storage(::Base.Type{<:$(esc(_storage_type))},
                                                     system::Peridynamics.AbstractSystem,
                                                     ::Val{$(QuoteNode(_decl.name))},
                                                     marker::Peridynamics.FullField)
                return $(alloc_solver_field_call(_decl))
            end
        end
        for _decl in _decls if !isnothing(_decl.shape)
    ]

    # the docstring is attached last, so that a `$(block_table(Name))` in it can already read
    # the declarations that were just registered
    local _doc = quote
        Base.@__doc__ $(esc(_storage_type))
    end

    local _checks = quote
        Peridynamics.typecheck_material($(esc(material)))
        Peridynamics.typecheck_storage($(esc(material)), $(esc(_storage_type)))
    end

    local _exprs = Expr(:block, _storage_struct, _dim_constructor, _get_n_dim,
                        _constructor, _storage_type_function,
                        _get_storage, _adapt_structure, _point_data_fields...,
                        _get_all_point_data_fields, _halo_to_loc_fields, _loc_to_halo_fields,
                        _is_halo_fields..., _storage_fields_expr, _init_field_storages...,
                        _constitutive_state, _damage_state, _doc, _checks)
    return _exprs
end

#=
`storage_type` returns the instantiation of the storage with the arrays of the CPU, which is
what a simulation that does not move its data anywhere else uses, and it takes the float type
of the simulation, which is the only parameter that is not fixed by the field declarations.
=#
function storage_type_function(material, storage_type, params, uses_sim_float,
                               cm_state_field=nothing, dmg_state_field=nothing)
    has_cm_state = !isnothing(cm_state_field)
    has_dmg_state = !isnothing(dmg_state_field)
    args = Any[esc(storage_type), DIM_TYPE_PARAM]
    uses_sim_float && push!(args, FLOAT_TYPE_PARAM)
    append!(args, storage_param_default(param) for param in params)
    # the nested states are the parameters that do not follow from the declarations,
    # because it is the constitutive model and the damage model of the material that
    # answer them; the order matches `storage_header_expr`
    has_cm_state && push!(args, :(Peridynamics.constitutive_storage_type(Peridynamics.get_constitutive_model(mat),
                                                                        $(FLOAT_TYPE_PARAM),
                                                                        Base.Val($(DIM_TYPE_PARAM)))))
    # the damage state is system-owned as well: which fields a model carries can depend
    # on the system family, e.g. the fracture bookkeeping of `CriticalStretch`, and the
    # dimension follows from the system type it is asked about
    has_dmg_state && push!(args, :(Peridynamics.damage_storage_type(Peridynamics.get_dmgmodel(mat),
                                                                    Peridynamics.system_type(mat,
                                                                                             $(FLOAT_TYPE_PARAM),
                                                                                             Base.Val($(DIM_TYPE_PARAM))),
                                                                    $(FLOAT_TYPE_PARAM))))
    instantiation = Expr(:curly, args...)
    return quote
        function Peridynamics.storage_type(mat::$(esc(material)),
                                           ::Base.Type{$(FLOAT_TYPE_PARAM)}=Peridynamics.default_float_type(),
                                           ::Base.Val{$(DIM_TYPE_PARAM)}=Base.Val(3)) where {$(FLOAT_TYPE_PARAM),$(DIM_TYPE_PARAM)}
            return $(instantiation)
        end
    end
end

"""
    @cm_storage model state

$(extension_api_note())

Declare the state a history-dependent constitutive model integrates over time, e.g. the
plastic strain of a plasticity model. This is [`@storage`](@ref) for a constitutive model
instead of a material, and the body accepts the same field declarations.

The generated state is reached inside [`first_piola_kirchhoff`](@ref) with
[`constitutive_state`](@ref), and a material carries it by declaring
`cm_state::ConstitutiveState`, see [`ConstitutiveState`](@ref).

# Differences to `@storage`

- Every field has to be declared with a **field shape**. A constitutive model has no
    `init_field` hook, because it does not know the material its state belongs to.
- The halo annotations [`@lth`](@ref) and [`@htl`](@ref) are **not allowed**. The state of a
    constitutive model is chunk-local, which is what bond state and point-local state are.
- The state is **not point data**, so it is not exported to VTK files. A quantity that
    should be exported belongs into the storage of the material.

# Example

```julia
Peridynamics.@cm_storage MyPlasticModel struct MyPlasticState
    bond_plastic_strain::BondSymTensor
    bond_eqps::BondScalar
end
```

`MyPlasticModel` is history dependent by this declaration alone, see
[`is_history_dependent`](@ref).

See also [`@storage`](@ref), [`@dmg_storage`](@ref), [`constitutive_state`](@ref),
[`constitutive_storage_type`](@ref).
"""
macro cm_storage(model, state)
    macrocheck_input_material(model)
    macrocheck_input_storage_struct(state)
    return __cm_storage(model, state, __module__)
end

function __cm_storage(model, state, mod::Module)
    local _state_data = get_storage_structdef(state, mod,
                                              :(Peridynamics.AbstractConstitutiveState))
    local _state_struct = _state_data.storage_struct
    local _state_type = _state_data.storage_type
    local _decls = _state_data.decls
    local _params = _state_data.params
    local _field_params = _state_data.field_params
    local _uses_sim_float = _state_data.uses_sim_float
    check_cm_storage_decls(_decls)

    local _alloc_calls = [cm_alloc_field_call(_decl) for _decl in _decls]

    local _dim_constructor = storage_dim_constructor_expr(_state_type, _decls, _params,
                                                          _uses_sim_float, _field_params)

    local _get_n_dim = get_n_dim_expr(_state_type)

    local _constructor = quote
        function $(esc(_state_type))(model::$(esc(model)),
                                     solver::Peridynamics.AbstractTimeSolver,
                                     system::Peridynamics.AbstractSystem)
            return $(esc(_state_type)){Peridynamics.get_n_dim(system)}($(_alloc_calls...))
        end
    end

    local _storage_type_function = cm_storage_type_function(model, _state_type, _params,
                                                            _uses_sim_float)

    local _get_cm_storage = quote
        function Peridynamics.get_cm_storage(model::$(esc(model)),
                                             solver::Peridynamics.AbstractTimeSolver,
                                             system::Peridynamics.AbstractSystem)
            return $(esc(_state_type))(model, solver, system)
        end
    end

    local _adapt_args = [
        :(Adapt.adapt(to, Base.getfield(s, $(QuoteNode(_decl.name))))) for _decl in _decls
    ]
    local _adapt_structure = if isempty(_params)
        Expr(:block)
    else
        quote
            function Adapt.adapt_structure(to, s::$(esc(_state_type)){N}) where {N}
                return $(esc(_state_type)){N}($(_adapt_args...))
            end
        end
    end

    local _storage_fields_expr = quote
        function Peridynamics.storage_fields_expr(::Base.Type{<:$(esc(_state_type))})
            return $(QuoteNode(_decls))
        end
    end

    local _checks = quote
        Peridynamics.typecheck_constitutive_model($(esc(model)))
    end

    return Expr(:block, _state_struct, _dim_constructor, _get_n_dim, _constructor,
                _storage_type_function, _get_cm_storage, _adapt_structure,
                _storage_fields_expr, _checks)
end

check_cm_storage_decls(decls) = check_nested_state_decls(:cm, decls)

# `@cm_storage` and `@dmg_storage` accept exactly the same field declarations, so they
# reject the same three things, with the wording of whichever state is being declared
function check_nested_state_decls(kind::Symbol, decls)
    what = kind === :cm ? "constitutive" : "damage"
    model = nested_state_model(kind)
    macroname = kind === :cm ? "@cm_storage" : "@dmg_storage"
    for decl in decls
        if is_halo_decl(decl)
            msg = "the $(what) state field `$(decl.name)` is annotated with "
            msg *= "`@$(decl.annotation)`, which `$(macroname)` does not support!\n"
            msg *= "  The state of a $(model) is chunk-local, so it is never exchanged "
            msg *= "between chunks. Bond state and point-local state need no exchange. A "
            msg *= "quantity that has to be exchanged belongs into the storage of the "
            msg *= "material.\n"
            throw(ArgumentError(msg))
        end
        if is_nested_state_decl(decl)
            marker = nested_state_marker(is_cm_state_decl(decl) ? :cm : :dmg)
            msg = "the $(what) state field `$(decl.name)` is declared with `$(marker)`, "
            msg *= "but a $(model) cannot carry the state of another model!\n"
            throw(ArgumentError(msg))
        end
        if isnothing(decl.shape)
            msg = "the $(what) state field `$(decl.name)` is declared with the container "
            msg *= "type `$(decl.type)` instead of a field shape!\n"
            msg *= "  A $(model) has no `init_field` hook, because it does not know the "
            msg *= "material its state belongs to, so every field of a `$(macroname)` "
            msg *= "definition needs a field shape, e.g.\n"
            msg *= "        $(decl.name)::BondScalar\n"
            throw(ArgumentError(msg))
        end
    end
    return nothing
end

function cm_alloc_field_call(decl::StorageFieldDecl)
    args = Any[:(Peridynamics.alloc_field), decl.shape, :system,
               :(Peridynamics.LocalPoints())]
    isnothing(decl.init) || push!(args, decl.init)
    return Expr(:call, args...)
end

function cm_storage_type_function(model, state_type, params, uses_sim_float)
    args = Any[esc(state_type), DIM_TYPE_PARAM]
    uses_sim_float && push!(args, FLOAT_TYPE_PARAM)
    append!(args, storage_param_default(param) for param in params)
    instantiation = Expr(:curly, args...)
    return quote
        function Peridynamics.constitutive_storage_type(::$(esc(model)),
                                                        ::Base.Type{$(FLOAT_TYPE_PARAM)}=Peridynamics.default_float_type(),
                                                        ::Base.Val{$(DIM_TYPE_PARAM)}=Base.Val(3)) where {$(FLOAT_TYPE_PARAM),$(DIM_TYPE_PARAM)}
            return $(instantiation)
        end
    end
end

function typecheck_constitutive_model(::Type{Model}) where {Model}
    if !(Model <: AbstractConstitutiveModel)
        msg = "$(Model) is not a valid constitutive model type!\n"
        msg *= "  A constitutive model has to be a subtype of "
        msg *= "`Peridynamics.AbstractConstitutiveModel`.\n"
        throw(ArgumentError(msg))
    end
    return nothing
end

function typecheck_constitutive_model(model)
    return throw(ArgumentError("$(model) is not a valid constitutive model type!\n"))
end

function init_field_storage_call(decl::StorageFieldDecl)
    args = Any[:(Peridynamics.alloc_field), decl.shape, :system, :extent]
    isnothing(decl.init) || push!(args, decl.init)
    return Expr(:call, args...)
end

function alloc_solver_field_call(decl::StorageFieldDecl)
    args = Any[:(Peridynamics.alloc_solver_field), :marker, decl.shape, :system,
               field_extent(decl), decl.init]
    return Expr(:call, args...)
end

"""
    @dmg_storage dmgmodel state
    @dmg_storage dmgmodel system state

$(extension_api_note())

Declare the state a damage model carries per bond or per point: the fracture bookkeeping it
maintains in [`calc_failure!`](@ref), and everything of its own, e.g. the accumulated
ductile damage of a Johnson-Cook model or the number of load cycles a bond has survived.
This is [`@cm_storage`](@ref) for a damage model instead of a constitutive model, and the
body accepts the same field declarations.

The generated state is reached inside [`calc_failure!`](@ref), [`calc_damage!`](@ref),
[`kinematic_weight`](@ref) and [`bond_integrity`](@ref) with [`damage_state`](@ref), and a
material carries it by declaring `dmg_state::DamageState`, see [`DamageState`](@ref). The
fields of the state are read flat off the storage, e.g. `storage.bond_active`, so kernels
never see the nesting.

A model that deletes bonds inherits the bookkeeping block of its system family, e.g.
`@inherit BondFracFields` for a bond system, and this is checked when a [`Job`](@ref) is
created. The optional `system` argument restricts a declaration to one system family, which
is how one model declares different states for different systems: [`CriticalStretch`](@ref)
declares [`BondFracFields`](@ref) for `AbstractBondSystem` and
[`InteractionFracFields`](@ref) for `InteractionSystem`. Without the argument the
declaration serves every system.

# Differences to `@storage`

- Every field has to be declared with a **field shape**. The initial value of a field the
    system knows better still comes from `init_field_system`, e.g. `n_active_bonds` starts
    as the neighbor count.
- The halo annotations [`@lth`](@ref) and [`@htl`](@ref) are **not allowed**. The state of a
    damage model is chunk-local, which is what bond state and point-local state are.
- A field with a point shape is point data of the storage that carries the state, so it can
    be exported to VTK files like a flat field, e.g. the `damage` of the fracture
    bookkeeping. A derived quantity is exported with an [`export_field`](@ref) method.

!!! note "A damage state does not make a model history dependent"
    Unlike [`@cm_storage`](@ref), this macro does **not** touch
    [`is_history_dependent`](@ref), so a stateful damage model stays compatible with every
    solver that supports fracture.

# Example

```julia
Peridynamics.@dmg_storage MyDamage struct MyDamageState
    @inherit BondFracFields
    bond_damage::BondScalar
end
```

See also [`@storage`](@ref), [`@cm_storage`](@ref), [`damage_state`](@ref),
[`damage_storage_type`](@ref), [`calc_failure!`](@ref).
"""
macro dmg_storage(dmgmodel, state)
    macrocheck_input_material(dmgmodel)
    macrocheck_input_storage_struct(state)
    return __dmg_storage(dmgmodel, state, __module__)
end

macro dmg_storage(dmgmodel, system, state)
    macrocheck_input_material(dmgmodel)
    macrocheck_input_system(system)
    macrocheck_input_storage_struct(state)
    return __dmg_storage(dmgmodel, state, __module__, system)
end

function macrocheck_input_system(system)
    system isa Symbol && return nothing
    (system isa Expr && system.head === :.) && return nothing
    msg = "argument `$system` is not a valid system input!\n"
    return throw(ArgumentError(msg))
end

function __dmg_storage(dmgmodel, state, mod::Module, system=AbstractSystem)
    local _state_data = get_storage_structdef(state, mod,
                                              :(Peridynamics.AbstractDamageState))
    local _state_struct = _state_data.storage_struct
    local _state_type = _state_data.storage_type
    local _decls = _state_data.decls
    local _params = _state_data.params
    local _field_params = _state_data.field_params
    local _uses_sim_float = _state_data.uses_sim_float
    check_dmg_storage_decls(_decls)

    local _alloc_calls = [dmg_alloc_field_call(_decl) for _decl in _decls]

    local _dim_constructor = storage_dim_constructor_expr(_state_type, _decls, _params,
                                                          _uses_sim_float, _field_params)

    local _get_n_dim = get_n_dim_expr(_state_type)

    local _constructor = quote
        function $(esc(_state_type))(dmgmodel::$(esc(dmgmodel)),
                                     solver::Peridynamics.AbstractTimeSolver,
                                     system::$(esc(system)))
            return $(esc(_state_type)){Peridynamics.get_n_dim(system)}($(_alloc_calls...))
        end
    end

    local _storage_type_function = dmg_storage_type_function(dmgmodel, system, _state_type,
                                                             _params, _uses_sim_float)

    local _get_dmg_storage = quote
        function Peridynamics.get_dmg_storage(dmgmodel::$(esc(dmgmodel)),
                                              solver::Peridynamics.AbstractTimeSolver,
                                              system::$(esc(system)))
            return $(esc(_state_type))(dmgmodel, solver, system)
        end
    end

    local _point_field_names = Tuple(QuoteNode(d.name) for d in _decls if is_point_decl(d))

    local _point_data_fields = [
        quote
            function Peridynamics.point_data_field(s::$(esc(_state_type)),
                                                   ::Val{$(_field)})
                return Base.getfield(s, $(_field))
            end
        end
        for _field in _point_field_names
    ]

    local _get_all_point_data_fields = quote
        function Peridynamics.point_data_fields(::Base.Type{<:$(esc(_state_type))})
            return $(Expr(:tuple, _point_field_names...))
        end
    end

    local _adapt_args = [
        :(Adapt.adapt(to, Base.getfield(s, $(QuoteNode(_decl.name))))) for _decl in _decls
    ]
    local _adapt_structure = if isempty(_params)
        Expr(:block)
    else
        quote
            function Adapt.adapt_structure(to, s::$(esc(_state_type)){N}) where {N}
                return $(esc(_state_type)){N}($(_adapt_args...))
            end
        end
    end

    local _storage_fields_expr = quote
        function Peridynamics.storage_fields_expr(::Base.Type{<:$(esc(_state_type))})
            return $(QuoteNode(_decls))
        end
    end

    # the docstring is attached last, so that a `$(block_table(Name))` in it can already
    # read the declarations that were just registered
    local _doc = quote
        Base.@__doc__ $(esc(_state_type))
    end

    local _checks = quote
        Peridynamics.typecheck_damage_model($(esc(dmgmodel)))
    end

    return Expr(:block, _state_struct, _dim_constructor, _get_n_dim, _constructor,
                _storage_type_function, _get_dmg_storage, _point_data_fields...,
                _get_all_point_data_fields, _adapt_structure, _storage_fields_expr, _doc,
                _checks)
end

#=
The initial value of a state field: the system is consulted first, exactly like for a flat
storage field, so a value only the system knows, e.g. the neighbor count that
`n_active_bonds` starts with, works inside a damage state as well. Everything else follows
from the shape and the declared init.
=#
@inline function init_state_field(system::AbstractSystem, field::Val, shape, init)
    value = init_field_system(system, field)
    isnothing(value) || return value
    return alloc_field(shape, system, LocalPoints(), init)
end

function dmg_alloc_field_call(decl::StorageFieldDecl)
    return :(Peridynamics.init_state_field(system, Base.Val($(QuoteNode(decl.name))),
                                           $(decl.shape), $(decl.init)))
end

#=
Unlike a storage and the state of a constitutive model, the state of a damage model is asked
about a system type and not about a `Val`, so it reads the dimension off that system.
=#
function dmg_storage_type_function(dmgmodel, system, state_type, params, uses_sim_float)
    args = Any[esc(state_type), :(Peridynamics.get_n_dim(System))]
    uses_sim_float && push!(args, FLOAT_TYPE_PARAM)
    append!(args, storage_param_default(param) for param in params)
    instantiation = Expr(:curly, args...)
    return quote
        function Peridynamics.damage_storage_type(::$(esc(dmgmodel)),
                                                  ::Base.Type{System},
                                                  ::Base.Type{$(FLOAT_TYPE_PARAM)}=Peridynamics.default_float_type()) where {System<:$(esc(system)),$(FLOAT_TYPE_PARAM)}
            return $(instantiation)
        end
    end
end

function typecheck_damage_model(::Type{Model}) where {Model}
    if !(Model <: AbstractDamageModel)
        msg = "$(Model) is not a valid damage model type!\n"
        msg *= "  A damage model has to be a subtype of "
        msg *= "`Peridynamics.AbstractDamageModel`.\n"
        throw(ArgumentError(msg))
    end
    return nothing
end

function typecheck_damage_model(dmgmodel)
    return throw(ArgumentError("$(dmgmodel) is not a valid damage model type!\n"))
end

check_dmg_storage_decls(decls) = check_nested_state_decls(:dmg, decls)

function get_storage_structdef(storage_expr, mod::Module,
                               default_supertype=:(Peridynamics.AbstractStorage))
    storage_type, supertype = get_storage_header(storage_expr, default_supertype)
    decls = get_field_decls(storage_expr.args[3].args, mod)
    (; params, field_params, uses_sim_float, cm_state_field,
       dmg_state_field) = derive_storage_type_params(decls)
    fields_exprs = [Expr(:(::), d.name, storage_field_decl_type(d, field_params))
                    for d in decls]
    fields_block = Expr(:block, fields_exprs...)
    header = storage_header_expr(storage_type, supertype, params, uses_sim_float,
                                 cm_state_field, dmg_state_field)
    storage_struct = Expr(:struct, storage_expr.args[1], header, fields_block)
    return (; storage_struct, storage_type, decls, params, field_params, uses_sim_float,
            cm_state_field, dmg_state_field)
end

"""
    storage_header_expr(storage_type, supertype, params, uses_sim_float)

$(internal_api_warning())

Assemble the header of the generated storage struct from the derived type parameters, see
[`derive_storage_type_params`](@ref). A storage without a derived parameter, i.e. one whose
fields are all declared with a type that is not an `Array`, keeps a plain header.
"""
function storage_header_expr(storage_type, supertype, params, uses_sim_float,
                             cm_state_field=nothing, dmg_state_field=nothing)
    param_exprs = Any[DIM_TYPE_PARAM]
    uses_sim_float && push!(param_exprs, Expr(:(<:), FLOAT_TYPE_PARAM, Real))
    for param in params
        push!(param_exprs, Expr(:(<:), param.name, storage_param_bound(param)))
    end
    # a nested state is whatever the model declares, so its parameter is unbounded;
    # `Nothing` for a model without state. `CMS` comes before `DMS`.
    isnothing(cm_state_field) || push!(param_exprs, CM_STATE_TYPE_PARAM)
    isnothing(dmg_state_field) || push!(param_exprs, DMG_STATE_TYPE_PARAM)
    return Expr(:(<:), Expr(:curly, storage_type, param_exprs...), supertype)
end

"""
    storage_dim_constructor_expr(storage_type, decls, params, uses_sim_float, field_params)

$(internal_api_warning())

Assemble the outer constructor that fixes the number of spatial dimensions of a generated
storage or model state. `N` is the one type parameter that no field answers, so the default
constructor cannot infer it: a storage takes it from the system it is built for. This
constructor names it and lets the field types answer every other parameter, which is what
the storage constructor and `Adapt.adapt_structure` call.
"""
function storage_dim_constructor_expr(storage_type, decls, params, uses_sim_float,
                                      field_params, cm_state_field=nothing,
                                      dmg_state_field=nothing)
    where_params = Any[DIM_TYPE_PARAM]
    uses_sim_float && push!(where_params, Expr(:(<:), FLOAT_TYPE_PARAM, Real))
    curly_params = Any[DIM_TYPE_PARAM]
    uses_sim_float && push!(curly_params, FLOAT_TYPE_PARAM)
    for param in params
        push!(where_params, Expr(:(<:), param.name, storage_param_bound(param)))
        push!(curly_params, param.name)
    end
    if !isnothing(cm_state_field)
        push!(where_params, CM_STATE_TYPE_PARAM)
        push!(curly_params, CM_STATE_TYPE_PARAM)
    end
    if !isnothing(dmg_state_field)
        push!(where_params, DMG_STATE_TYPE_PARAM)
        push!(curly_params, DMG_STATE_TYPE_PARAM)
    end
    # a storage whose only parameter is `N` needs no method of its own: `S{N}(fields...)` is
    # then the default constructor, and generating it again would only recurse
    length(curly_params) == 1 && return Expr(:block)
    args = [Expr(:(::), d.name, storage_field_decl_type(d, field_params)) for d in decls]
    names = [d.name for d in decls]
    call = Expr(:call, Expr(:curly, esc(storage_type), DIM_TYPE_PARAM), args...)
    signature = Expr(:where, call, where_params...)
    body = Expr(:return,
                Expr(:call, Expr(:curly, esc(storage_type), curly_params...), names...))
    return Expr(:function, signature, Expr(:block, body))
end

"""
    get_n_dim_expr(storage_type)

$(internal_api_warning())

Assemble the [`get_n_dim`](@ref) method of a generated storage or model state, which reads
the leading type parameter of the struct.
"""
function get_n_dim_expr(storage_type)
    return quote
        @inline function Peridynamics.get_n_dim(::$(esc(storage_type)){$(DIM_TYPE_PARAM)}) where {$(DIM_TYPE_PARAM)}
            return $(DIM_TYPE_PARAM)
        end
    end
end

"""
    get_storage_header(storage_expr)

$(internal_api_warning())

Return the name and the supertype of the storage struct of a [`@storage`](@ref) definition.
A definition that declares its own type parameters is rejected, because `@storage` derives
them from the field declarations.
"""
function get_storage_header(storage_expr, default_supertype=:(Peridynamics.AbstractStorage))
    header = storage_expr.args[2]
    if header isa Symbol
        # case `struct MyStorage`
        return header, default_supertype
    elseif header isa Expr && header.head === :(<:) && header.args[1] isa Symbol
        # case `struct MyStorage <: AbstractStorage`
        return header.args[1], header.args[2]
    end
    return throw(ArgumentError(storage_header_msg(header)))
end

function storage_header_msg(header)
    is_parametric = header isa Expr &&
                    (header.head === :curly ||
                     (header.head === :(<:) && header.args[1] isa Expr &&
                      header.args[1].head === :curly))
    is_parametric || return "storage header `$(header)` not supported!\n"
    msg = "a storage cannot declare its own type parameters, got `$(header)`!\n"
    msg *= "  `@storage` derives the type parameters of a storage from its field "
    msg *= "declarations, so that the storage is generic in the float type of the "
    msg *= "simulation and can be moved to another array backend. Declare the storage "
    msg *= "without type parameters and pin the element type of a field in its field shape "
    msg *= "instead, e.g.\n"
    msg *= "        position::PointVector{Float64}\n"
    return msg
end

function loc_to_halo_fields(storage)
    return throw(InterfaceError(storage, "loc_to_halo_fields"))
end

function halo_to_loc_fields(storage)
    return throw(InterfaceError(storage, "halo_to_loc_fields"))
end

is_halo_field(::AbstractStorage, ::Val{F}) where {F} = false

macro halo_fields(storage, fields...)
    macrocheck_input_storage_type(storage)
    macrocheck_input_fields(fields...)
    local _checks = quote
        Peridynamics.typecheck_is_storage($(esc(storage)))
        Peridynamics.typecheck_storage_fields($(esc(storage)), $(Expr(:tuple, fields...)))
    end
    local _is_halo_fields = [quote
                                 function Peridynamics.is_halo_field(::$(esc(storage)),
                                                                     ::Val{$(esc(_field))})
                                     return true
                                 end
                             end
                             for _field in fields]
    # the checks have to come last; otherwise errors cannot be tested with @test_throws ...
    return Expr(:block, _is_halo_fields..., _checks)
end

function macrocheck_input_storage_type(storage)
    storage isa Symbol && return nothing
    (storage isa Expr && storage.head === :.) && return nothing
    (storage isa Expr && storage.head === :escape) && return nothing
    msg = "argument `$storage` is not a valid storage input!\n"
    return throw(ArgumentError(msg))
end

function macrocheck_input_storage_struct(storage)
    (storage isa Expr && storage.head === :struct) && return nothing
    (storage isa Expr && storage.head === :escape) && return nothing
    msg = "specified input is not a valid storage struct expression!\n"
    return throw(ArgumentError(msg))
end

function macrocheck_input_timesolver(timesolver)
    timesolver isa Symbol && return nothing
    (timesolver isa Expr && timesolver.head === :.) && return nothing
    msg = "argument `$timesolver` is not a valid time solver input!\n"
    return throw(ArgumentError(msg))
end

function macrocheck_input_fields(fields...)
    for field in fields
        macrocheck_input_field(field)
    end
    return nothing
end

function macrocheck_input_field(field)
    if !(field isa QuoteNode && field.value isa Symbol)
        msg = "argument $field is not a valid field input!\n"
        throw(ArgumentError(msg))
    end
    return nothing
end

function typecheck_storage(::Type{Material}, ::Type{Storage}) where {Material,Storage}
    typecheck_is_storage(Storage)
    typecheck_req_fields_missing(Storage, required_fields(Material))
    return nothing
end

function typecheck_storage(material, storage)
    return throw(ArgumentError("$storage is not a valid storage type!\n"))
end

function typecheck_is_storage(::Type{Storage}) where {Storage}
    if !(Storage <: AbstractStorage)
        msg = "$Storage is not a valid storage type!\n"
        throw(ArgumentError(msg))
    end
    return nothing
end

function typecheck_is_storage(storage)
    return throw(ArgumentError("$storage is not a valid storage type!\n"))
end

function typecheck_storage_fields(::Type{S}, fields::NTuple{N,Symbol}) where {S,N}
    storage_fields = fieldnames(S)
    for field in fields
        if !in(field, storage_fields)
            msg = "storage $(S) has no field `$(field)`!\n"
            throw(ArgumentError(msg))
        end
    end
    return nothing
end

function typecheck_req_fields_missing(::Type{Storage}, req_fields) where {Storage}
    storage_fields = fieldnames(Storage)
    for req_field in req_fields
        if !in(req_field, storage_fields)
            error("required field $req_field not found in $(Storage)!\n")
        end
    end
    return false
end

"""
    required_fields(::Type{Material})

$(internal_api_warning())

Return all storage fields that can be determined from the material *type* alone. This is
the cheap check done by [`@storage`](@ref) at macro expansion time.

Everything that depends on the material *instance*, the damage model or the time solver
cannot be known here and is therefore checked at setup time with
[`check_storage_contract`](@ref). The fracture bookkeeping belongs to the damage model, so
it is part of the setup-time check as well, see [`check_damage_model`](@ref).
"""
function required_fields(::Type{Material}) where {Material<:AbstractMaterial}
    return ()
end

"""
    req_storage_fields(mat)
    req_storage_fields(mat, dmgmodel)
    req_storage_fields(solver)

$(internal_api_warning())

Return the storage fields that are required by a material family, by a damage model in
combination with a material, or by a time solver. All methods return a `Tuple` of `Symbol`s
and default to an empty tuple, so only the parts of the contract that really exist have to
be declared.

These declarations are collected by [`check_storage_contract`](@ref) when a [`Job`](@ref)
is created.

# Example
```julia
Peridynamics.req_storage_fields(::MyMaterialFamily) = (:defgrad, :weighted_volume)
Peridynamics.req_storage_fields(::MyMaterialFamily, ::MyDamageModel) = (:bond_damage,)
```
"""
function req_storage_fields end

req_storage_fields(::AbstractMaterial) = ()

"""
    storage_contract(mat::AbstractMaterial, solver::AbstractTimeSolver)

$(internal_api_warning())

Return the complete storage contract of `mat` in combination with `solver` as a `Tuple` of
`(fields, reason)` pairs, where `reason` describes why the fields are required.
"""
function storage_contract(mat::AbstractMaterial, solver::AbstractTimeSolver)
    M, S = typeof(mat), typeof(solver)
    dmgmodel = get_dmgmodel(mat)
    return ((req_storage_fields(mat), "the material `$(nameof(M))`"),
            (req_storage_fields(mat, dmgmodel), "the damage model `$(_name_of(dmgmodel))`"),
            (req_storage_fields(solver), "the time solver `$(nameof(S))`"))
end

# also `:Nothing` for a material without a damage model
@inline _name_of(x) = nameof(typeof(x))

"""
    check_storage_contract(spatial_setup, solver::AbstractTimeSolver)

$(internal_api_warning())

Check if the storage of every material of `spatial_setup` contains all fields that are
required by the material itself, by its damage model and by the time solver `solver`.
Throws a [`StorageContractError`](@ref) that names the missing fields and the reason why
they are required.

This check is done once when a [`Job`](@ref) is created. In contrast to the check inside
[`@storage`](@ref), the damage model and the time solver are known here, so the parts of
the contract that depend on them can finally be verified.
"""
function check_storage_contract(mat::AbstractMaterial, solver::AbstractTimeSolver)
    S = storage_type(mat)
    check_state_field_collisions(S)
    storage_fields = fieldnames(S)
    missing_fields = Vector{Pair{Symbol,String}}()
    for (fields, reason) in storage_contract(mat, solver)
        for field in fields
            in(field, storage_fields) && continue
            any(x -> first(x) === field, missing_fields) && continue
            push!(missing_fields, field => reason)
        end
    end
    isempty(missing_fields) && return nothing
    throw(StorageContractError(S, typeof(mat), typeof(solver), missing_fields))
end

#=
Reading a storage flat only works when every property has exactly one home. A flat field
that shadows a state field, or a name that both states carry, is therefore rejected here,
where the concrete state types are finally known. `getproperty` itself throws on the
ambiguous read as a backstop for flows that never create a `Job`.
=#
function check_state_field_collisions(::Type{S}) where {S}
    flat_fields = fieldnames(S)
    seen = Symbol[]
    for field in flat_fields
        FT = fieldtype(S, field)
        FT <: Union{AbstractConstitutiveState,AbstractDamageState} || continue
        for name in fieldnames(FT)
            if in(name, flat_fields)
                msg = "the storage `$(nameof(S))` declares the field `$(name)` although "
                msg *= "the state `$(nameof(FT))` in `$(field)` carries it as well!\n"
                msg *= "  Remove the flat declaration, the field of the state is read "
                msg *= "flat off the storage anyway.\n"
                throw(ArgumentError(msg))
            end
            if in(name, seen)
                msg = "both nested states of the storage `$(nameof(S))` carry a field "
                msg *= "`$(name)`!\n"
                msg *= "  Every property of a storage needs exactly one home, rename the "
                msg *= "field in one of the two models.\n"
                throw(ArgumentError(msg))
            end
            push!(seen, name)
        end
    end
    return nothing
end

function check_storage_contract(body::AbstractBody, solver::AbstractTimeSolver)
    return check_storage_contract(body.mat, solver)
end

function check_storage_contract(ms::AbstractMultibodySetup, solver::AbstractTimeSolver)
    for body in each_body(ms)
        check_storage_contract(body, solver)
    end
    return nothing
end

@inline function get_point_data(s::AbstractStorage, field::Symbol)
    return point_data_field(s, Val(field))
end

function point_data_field(::S, ::Val{Field}) where {S,Field}
    return throw(InterfaceError(S, "point_data_field(::$S, ::Val{$Field})"))
end

function point_data_fields(::Type{S}) where {S<:AbstractStorage}
    return throw(InterfaceError(S, "point_data_fields(::Type{$S})"))
end

# a storage whose damage model has no state serves no point data through `dmg_state`
point_data_fields(::Type{Nothing}) = ()

function point_data_field(::Nothing, ::Val{Field}) where {Field}
    msg = "the storage has no point data field `$(Field)` and the damage model of the "
    msg *= "material carries no state that could provide it!\n"
    return throw(ArgumentError(msg))
end

#=
The point data a storage serves through its `dmg_state` field: what the state declares, or
nothing for a model without state. The untyped fallback catches the `dmg_state` field type
of a storage that is not concrete, e.g. the plain `BBStorage`, where the state is still a
free type parameter.
=#
nested_point_data_fields(::Type{Nothing}) = ()
nested_point_data_fields(::Type{S}) where {S<:AbstractDamageState} = point_data_fields(S)
nested_point_data_fields(@nospecialize(x)) = ()

function get_loc_to_halo_fields(s::AbstractStorage)
    return Tuple(get_point_data(s, field) for field in loc_to_halo_fields(s))
end

function get_halo_to_loc_fields(s::AbstractStorage)
    return Tuple(get_point_data(s, field) for field in halo_to_loc_fields(s))
end

function get_halo_fields(s::S) where {S<:AbstractStorage}
    return Tuple(get_point_data(s, f) for f in fieldnames(S) if is_halo_field(s, Val(f)))
end

function get_halo_fieldnames(s::S) where {S<:AbstractStorage}
    return Tuple(f for f in fieldnames(S) if is_halo_field(s, Val(f)))
end

function get_n_halo_fields(s::S) where {S<:AbstractStorage}
    n_halo_fields = 0
    for f in fieldnames(S)
        if is_halo_field(s, Val(f))
            n_halo_fields += 1
        end
    end
    return n_halo_fields
end

function get_loc_point_data(storage::AbstractStorage, system::AbstractSystem, field::Symbol)
    val_field = Val(field)
    is_halo_field(storage, val_field) || return point_data_field(storage, val_field)
    return get_loc_view(point_data_field(storage, val_field), system)
end

#=
Reading a storage flat, the twin of the parameter forwarding in `core/param_fields.jl`:
`getproperty` forwards a name that is not a field into the nested states, so a kernel reads
`storage.bond_active` without knowing that the damage model carries the field. The
`@generated` function computes the exact `getfield` chain per (type, name), so a property
literal compiles to a direct load and the forwarding costs nothing, which is asserted by
the "storage property forwarding" item of `test/perf/perf.jl`. Everything generated by the
macros reads fields with `getfield`, so the forwarding cannot recurse.
=#
Base.@constprop :aggressive @inline function Base.getproperty(storage::AbstractStorage,
                                                              name::Symbol)
    return get_storage_property(storage, Val(name))
end

# `storage.field .= value` reaches the field through `dotgetproperty`, one call deeper than
# a plain read, and the property literal has to survive into the `Val` there as well
Base.@constprop :aggressive @inline function Base.dotgetproperty(storage::AbstractStorage,
                                                                 name::Symbol)
    return get_storage_property(storage, Val(name))
end

@generated function get_storage_property(storage::S,
                                         ::Val{F}) where {S<:AbstractStorage,F}
    F in fieldnames(S) && return :(Base.getfield(storage, $(QuoteNode(F))))
    exprs, owners = Any[], Symbol[]
    for field in fieldnames(S)
        FT = fieldtype(S, field)
        FT <: Union{AbstractConstitutiveState,AbstractDamageState} || continue
        F in fieldnames(FT) || continue
        push!(owners, field)
        push!(exprs, :(Base.getfield(Base.getfield(storage, $(QuoteNode(field))),
                                     $(QuoteNode(F)))))
    end
    length(owners) == 1 && return exprs[1]
    # not found anywhere: `getfield` throws the native no-field error of this Julia version
    isempty(owners) && return :(Base.getfield(storage, $(QuoteNode(F))))
    return :(Peridynamics.ambiguous_storage_property($(QuoteNode(F)), storage,
                                                     $(Tuple(owners))))
end

function ambiguous_storage_property(name::Symbol, @nospecialize(storage), owners)
    msg = "the field `$(name)` exists in $(join(("`$(o)`" for o in owners), " and "))"
    msg *= " of `$(nameof(typeof(storage)))`!\n"
    msg *= "  Read it from the model state directly, e.g. "
    msg *= "`storage.$(first(owners)).$(name)`.\n"
    return throw(ArgumentError(msg))
end

function Base.propertynames(storage::AbstractStorage, private::Bool=false)
    return storage_property_names(storage)
end

# the fields plus everything the nested states hold, which is what `getproperty` accepts
@generated function storage_property_names(storage::S) where {S<:AbstractStorage}
    names = Symbol[]
    for field in fieldnames(S)
        push!(names, field)
        FT = fieldtype(S, field)
        FT <: Union{AbstractConstitutiveState,AbstractDamageState} || continue
        append!(names, fieldnames(FT))
    end
    return Tuple(names)
end
