#=
Storage field declarations.

This file contains everything that describes *what a storage field is* before a concrete
storage struct is generated by `@storage` (`core/storages.jl`):

- the field annotation macros `@lth` and `@htl`,
- the field shapes (`PointVector`, `BondTensor`, ...), which say what a field means
  instead of which container happens to hold it, and from which the container type and
  the allocation of the field are derived,
- the markers `FullField` and `EmptyField`, with which a time solver says whether it needs
  a field without having to know how the field is shaped,
- `@storage_fields` and `@inherit`, which make a block of field declarations reusable,
- the derivation of the type parameters of the generated storage struct from the
  declarations, which is what makes a storage generic in its float type and movable to
  another array backend.

It is included early so that field blocks can be declared next to the system, solver or
material family whose contract they express.
=#

# --------------------------------------------------------------------------------------
# field extents
# --------------------------------------------------------------------------------------

"""
    LocalPoints

$(extension_api_note())

Marker for fields that have one entry per local point of a chunk. This is the extent of
every field that is not annotated for halo exchange.
"""
struct LocalPoints end

"""
    HaloPoints

$(extension_api_note())

Marker for fields that have one entry per local *and* halo point of a chunk. This is the
extent of every field annotated with [`@lth`](@ref) or [`@htl`](@ref), because
these fields are exchanged between chunks.
"""
struct HaloPoints end

# --------------------------------------------------------------------------------------
# field shapes
# --------------------------------------------------------------------------------------

"""
    SimFloat

$(extension_api_note())

Placeholder element type of a field shape that is written without one, e.g. `PointVector`
instead of `PointVector{Float64}`. It is resolved to `float_type(system)` when the field is
allocated, so such a field follows the floating point type of the simulation, while a shape
with an explicit element type keeps it for every simulation.
"""
struct SimFloat end

"""
    AbstractPointFieldShape{T}

$(internal_api_warning())

Supertype of all field shapes with one column per point. Every field with such a shape is
point data and can therefore be exported. The number of entries is determined by the field
annotation: [`@lth`](@ref) and [`@htl`](@ref) give one entry per local and halo point, an
unannotated field one entry per local point.
"""
abstract type AbstractPointFieldShape{T} <: AbstractFieldShape{T} end

"""
    AbstractBondFieldShape{T}

$(internal_api_warning())

Supertype of all field shapes with one column per bond.
"""
abstract type AbstractBondFieldShape{T} <: AbstractFieldShape{T} end

"""
    PointScalar
    PointScalar{T}

$(extension_api_note())

Field shape of a scalar quantity per point, stored as a `Vector{T}`. Without an element type
it follows the float type of the simulation, see [`SimFloat`](@ref). See [`@storage`](@ref)
for how field shapes are used.
"""
struct PointScalar{T} <: AbstractPointFieldShape{T} end

"""
    PointVector
    PointVector{T}

$(extension_api_note())

Field shape of a vectorial quantity per point, stored as a `Matrix{T}` with one column per
point and `get_n_dim(system)` rows. See [`@storage`](@ref).
"""
struct PointVector{T} <: AbstractPointFieldShape{T} end

"""
    PointTensor
    PointTensor{T}

$(extension_api_note())

Field shape of a second order tensor per point, stored as a `Matrix{T}` with one column per
point and `get_n_dim(system)^2` rows. See [`@storage`](@ref).
"""
struct PointTensor{T} <: AbstractPointFieldShape{T} end

"""
    PointSymTensor
    PointSymTensor{T}

$(extension_api_note())

Field shape of a symmetric second order tensor per point in Voigt notation, stored as a
`Matrix{T}` with one column per point and `d * (d + 1) ÷ 2` rows, where
`d = get_n_dim(system)`. See [`@storage`](@ref).
"""
struct PointSymTensor{T} <: AbstractPointFieldShape{T} end

"""
    PointField{N}
    PointField{N,T}

$(extension_api_note())

Field shape of a quantity per point with `N` rows, stored as a `Matrix{T}` with one column
per point. In contrast to every other point shape the number of rows does not follow the
spatial dimension, so this is the shape for a per-point quantity that is not a vector or a
tensor. See [`@storage`](@ref).
"""
struct PointField{N,T} <: AbstractPointFieldShape{T} end

"""
    BondScalar
    BondScalar{T}

$(extension_api_note())

Field shape of a scalar quantity per bond, stored as a `Vector{T}`. See [`@storage`](@ref).
"""
struct BondScalar{T} <: AbstractBondFieldShape{T} end

"""
    BondVector
    BondVector{T}

$(extension_api_note())

Field shape of a vectorial quantity per bond, stored as a `Matrix{T}` with one column per
bond and `get_n_dim(system)` rows. See [`@storage`](@ref).
"""
struct BondVector{T} <: AbstractBondFieldShape{T} end

"""
    BondTensor
    BondTensor{T}

$(extension_api_note())

Field shape of a second order tensor per bond, stored as a `Matrix{T}` with one column per
bond and `get_n_dim(system)^2` rows. See [`@storage`](@ref).
"""
struct BondTensor{T} <: AbstractBondFieldShape{T} end

"""
    BondSymTensor
    BondSymTensor{T}

$(extension_api_note())

Field shape of a symmetric second order tensor per bond in Voigt notation, stored as a
`Matrix{T}` with one column per bond and `d * (d + 1) ÷ 2` rows, where
`d = get_n_dim(system)`. See [`@storage`](@ref).
"""
struct BondSymTensor{T} <: AbstractBondFieldShape{T} end

"""
    BondField{N}
    BondField{N,T}

$(extension_api_note())

Field shape of a quantity per bond with `N` rows, stored as a `Matrix{T}` with one column
per bond. The number of rows does not follow the spatial dimension, see
[`PointField`](@ref).
"""
struct BondField{N,T} <: AbstractBondFieldShape{T} end

"""
    AbstractDofFieldShape{T}

$(internal_api_warning())

Supertype of all field shapes with one entry per degree of freedom. These fields are neither
point nor bond data, so they cannot be exported.
"""
abstract type AbstractDofFieldShape{T} <: AbstractFieldShape{T} end

"""
    DofVector
    DofVector{T}

$(extension_api_note())

Field shape of a quantity per degree of freedom, stored as a `Vector{T}` with
`get_n_loc_dof(system)` entries, or `get_n_dof(system)` entries if the field is declared
with [`@lth`](@ref) or [`@htl`](@ref). See [`@storage`](@ref).
"""
struct DofVector{T} <: AbstractDofFieldShape{T} end

"""
    field_shape(x)

$(internal_api_warning())

Return the field shape instance a storage field is declared with, or `nothing` if `x` is a
plain container type such as `Matrix{Float64}`. This is how [`@storage`](@ref) tells the
two kinds of field declaration apart without having to know the shapes by name, so a new
shape only needs methods of `field_shape`, [`container_type`](@ref) and
[`field_n_rows`](@ref) to be usable.
"""
function field_shape end

field_shape(::Type) = nothing

# a shape written without an element type follows the float type of the simulation
for S in (:PointScalar, :PointVector, :PointTensor, :PointSymTensor,
          :BondScalar, :BondVector, :BondTensor, :BondSymTensor, :DofVector)
    @eval $(S)() = $(S){SimFloat}()
    @eval field_shape(::Base.Type{$(S)}) = $(S){SimFloat}()
    @eval field_shape(::Base.Type{$(S){T}}) where {T} = $(S){T}()
end

for S in (:PointField, :BondField)
    @eval $(S){N}() where {N} = $(S){N,SimFloat}()
    @eval field_shape(::Base.Type{$(S){N}}) where {N} = $(S){N,SimFloat}()
    @eval field_shape(::Base.Type{$(S){N,T}}) where {N,T} = $(S){N,T}()
end

"""
    field_n_dims(shape)

$(internal_api_warning())

Return the number of dimensions of the array that holds a field of the given
[`field_shape`](@ref).
"""
field_n_dims(::AbstractFieldShape) = 2
field_n_dims(::PointScalar) = 1
field_n_dims(::BondScalar) = 1
field_n_dims(::AbstractDofFieldShape) = 1

"""
    container_type(shape)
    container_type(shape, eltype_expr)

$(internal_api_warning())

Return the array type that holds a field of the given [`field_shape`](@ref). With one
argument this is a concrete type, where a shape that does not pin its element type uses
[`default_float_type`](@ref). With two arguments it is the type *expression* used in the
generated storage struct, where `eltype_expr` is either a type or the symbol of a type
parameter of the storage.
"""
function container_type end

container_type(shape::AbstractFieldShape) = container_type(shape, concrete_eltype(shape))

function container_type(shape::AbstractFieldShape, eltype_expr)
    n_dims = field_n_dims(shape)
    n_dims == 1 && return :(Base.Vector{$(eltype_expr)})
    n_dims == 2 && return :(Base.Matrix{$(eltype_expr)})
    return :(Base.Array{$(eltype_expr),$(n_dims)})
end

function container_type(shape::AbstractFieldShape, ::Base.Type{T}) where {T}
    n_dims = field_n_dims(shape)
    n_dims == 1 && return Vector{T}
    n_dims == 2 && return Matrix{T}
    return Array{T,n_dims}
end

"""
    field_n_rows(shape, system)

$(internal_api_warning())

Return the number of rows of a field with the given [`field_shape`](@ref), or `nothing` if
the field is stored as a `Vector`. Everything that depends on the spatial dimension is
resolved here through `get_n_dim(system)`, so this is the single place that has to change
when a system with a different dimension is added.
"""
function field_n_rows end

field_n_rows(::PointScalar, system) = nothing
field_n_rows(::BondScalar, system) = nothing
field_n_rows(::AbstractDofFieldShape, system) = nothing
field_n_rows(::Union{PointVector,BondVector}, system) = get_n_dim(system)
field_n_rows(::Union{PointTensor,BondTensor}, system) = get_n_dim(system)^2
function field_n_rows(::Union{PointSymTensor,BondSymTensor}, system)
    d = get_n_dim(system)
    return d * (d + 1) ÷ 2
end
field_n_rows(::Union{PointField{N},BondField{N}}, system) where {N} = N

"""
    field_n_entries(shape, system, extent)

$(internal_api_warning())

Return the number of entries (columns) of a field with the given [`field_shape`](@ref).
For point shapes this is the number of local points ([`LocalPoints`](@ref)) or the number
of local and halo points ([`HaloPoints`](@ref)), depending on the field annotation. For
bond shapes it is the number of bonds.
"""
function field_n_entries end

field_n_entries(::AbstractPointFieldShape, system, ::LocalPoints) = get_n_loc_points(system)
field_n_entries(::AbstractPointFieldShape, system, ::HaloPoints) = get_n_points(system)
field_n_entries(::AbstractBondFieldShape, system, extent) = get_n_bonds(system)
field_n_entries(::AbstractDofFieldShape, system, ::LocalPoints) = get_n_loc_dof(system)
field_n_entries(::AbstractDofFieldShape, system, ::HaloPoints) = get_n_dof(system)

"""
    field_eltype(shape)
    field_eltype(shape, system)

$(internal_api_warning())

Return the element type of a field with the given [`field_shape`](@ref). With one argument
this is [`SimFloat`](@ref) for a shape that does not pin its element type, with a system it
is the resolved type, i.e. `float_type(system)`.
"""
function field_eltype end

field_eltype(::AbstractFieldShape{T}) where {T} = T
field_eltype(shape::AbstractFieldShape, system) = _resolve_eltype(field_eltype(shape),
                                                                 system)

@inline _resolve_eltype(::Base.Type{SimFloat}, system) = float_type(system)
@inline _resolve_eltype(::Base.Type{T}, system) where {T} = T

"""
    concrete_eltype(shape)

$(internal_api_warning())

Return the element type a field with the given [`field_shape`](@ref) has in a simulation
with the [`default_float_type`](@ref).
"""
concrete_eltype(shape::AbstractFieldShape) = _resolve_default_eltype(field_eltype(shape))

@inline _resolve_default_eltype(::Base.Type{SimFloat}) = default_float_type()
@inline _resolve_default_eltype(::Base.Type{T}) where {T} = T

"""
    alloc_field(shape, system, extent)
    alloc_field(shape, system, extent, init)

$(internal_api_warning())

Allocate the array of a storage field with the given [`field_shape`](@ref). The element type
is [`field_eltype`](@ref)`(shape, system)`, the size follows from the shape, the system and
the `extent`. The initial value `init` is

| `init` | result |
|:---|:---|
| `nothing` | zeros |
| a `Number` | every entry that value |
| a `LinearAlgebra.UniformScaling`, e.g. `I` or `2I` | every column that tensor |

A `UniformScaling` requires a shape whose rows are the entries of a square tensor.
"""
function alloc_field end

function alloc_field(shape::AbstractFieldShape, system, extent)
    return alloc_field(shape, system, extent, nothing)
end

function alloc_field(shape::AbstractFieldShape, system, extent, init)
    T = field_eltype(shape, system)
    n_rows = field_n_rows(shape, system)
    n_entries = field_n_entries(shape, system, extent)
    return alloc_field_array(shape, T, n_rows, n_entries, init)
end

"""
    alloc_empty_field(::Type{Storage}, field)

$(internal_api_warning())

Allocate the zero-sized array of the type that `field` has in `Storage`. This is what a
time solver gets for a field it does not need, see [`EmptyField`](@ref). The type comes
from the storage and not from the field shape, so this works for a field declared with a
container type as well, and gives arrays of the right backend for a storage that lives on
a device.
"""
@inline function alloc_empty_field(::Base.Type{S}, ::Val{Field}) where {S,Field}
    return alloc_empty_array(Base.fieldtype(S, Field))
end

@inline function alloc_empty_array(::Base.Type{A}) where {A<:AbstractArray}
    return A(undef, ntuple(_ -> 0, Val(ndims(A))))
end

function alloc_empty_array(::Base.Type{T}) where {T}
    msg = "cannot allocate an empty `$(T)`!\n"
    msg *= "  A storage field that a time solver does not need has to be an array.\n"
    return throw(ArgumentError(msg))
end

function alloc_field_array(::AbstractFieldShape, ::Base.Type{T}, ::Nothing, n_entries,
                           ::Nothing) where {T}
    return zeros(T, n_entries)
end

function alloc_field_array(::AbstractFieldShape, ::Base.Type{T}, n_rows::Int, n_entries,
                           ::Nothing) where {T}
    return zeros(T, n_rows, n_entries)
end

function alloc_field_array(::AbstractFieldShape, ::Base.Type{T}, ::Nothing, n_entries,
                           init::Number) where {T}
    return fill(convert(T, init), n_entries)
end

function alloc_field_array(::AbstractFieldShape, ::Base.Type{T}, n_rows::Int, n_entries,
                           init::Number) where {T}
    return fill(convert(T, init), n_rows, n_entries)
end

function alloc_field_array(shape::AbstractFieldShape, ::Base.Type{T}, ::Nothing, n_entries,
                           init::UniformScaling) where {T}
    msg = "cannot initialize the field shape $(nameof(typeof(shape))) with `$(init)`!\n"
    msg *= "  Only a field whose rows are the entries of a square tensor can be "
    msg *= "initialized with a `UniformScaling`.\n"
    return throw(ArgumentError(msg))
end

function alloc_field_array(shape::AbstractFieldShape, ::Base.Type{T}, n_rows::Int,
                           n_entries, init::UniformScaling) where {T}
    d = isqrt(n_rows)
    if d * d != n_rows
        msg = "cannot initialize a field with $(n_rows) rows with `$(init)`, because the "
        msg *= "rows are not the entries of a square tensor!\n"
        throw(ArgumentError(msg))
    end
    field = zeros(T, n_rows, n_entries)
    for k in 1:d
        field[(k - 1) * d + k, :] .= convert(T, init.λ)
    end
    return field
end

function alloc_field_array(shape::AbstractFieldShape, ::Base.Type, n_rows, n_entries, init)
    msg = "cannot initialize the field shape $(nameof(typeof(shape))) with `$(init)`!\n"
    msg *= "  The initial value of a storage field is either a `Number`, which fills every "
    msg *= "entry, or a `UniformScaling`, e.g. `I`, which writes that tensor into every "
    msg *= "column.\n"
    msg *= "  Everything else needs an `init_field` method, see `@storage`.\n"
    return throw(ArgumentError(msg))
end

# --------------------------------------------------------------------------------------
# what a time solver answers with
# --------------------------------------------------------------------------------------

#=
A time solver knows which fields it works with, but not how they are shaped, and it must
not know: the number of rows of a vectorial field follows the spatial dimension of the
system and the element type follows the float type of the simulation. So instead of
allocating a field itself, `init_field_solver` answers with one of these markers and
leaves the allocation to the field shape the storage declared, see `init_field`.
=#

"""
    FullField()
    FullField(extent)

$(extension_api_note())

The answer of a time solver that needs a storage field: allocate it from its field shape.
Without an argument the field gets the extent it is declared with, which is
[`HaloPoints`](@ref) for a field annotated with [`@lth`](@ref) or [`@htl`](@ref) and
[`LocalPoints`](@ref) otherwise. With an `extent` the declaration is overruled, which is
how [`NewtonKrylov`](@ref) gets `b_int` with halo entries although the field is declared
without a halo annotation.
"""
struct FullField{E} <: AbstractSolverField
    extent::E
end

FullField() = FullField(nothing)

"""
    EmptyField()

$(extension_api_note())

The answer of a time solver that does not need a storage field: allocate it as the
zero-sized array of the type it has in the storage, see [`alloc_empty_field`](@ref).
"""
struct EmptyField <: AbstractSolverField end

"""
    alloc_solver_field(marker, shape, system, extent, init)

$(internal_api_warning())

Allocate the array of a storage field that a time solver answered for with the
[`FullField`](@ref) `marker`, where `shape`, `extent` and `init` are the field shape, the
extent and the initial value of the declaration. Methods of this function are called by the
`init_field_storage` methods that [`@storage`](@ref) generates.
"""
function alloc_solver_field end

function alloc_solver_field(::FullField{Nothing}, shape, system, extent, init)
    return alloc_field(shape, system, extent, init)
end

function alloc_solver_field(marker::FullField, shape, system, _, init)
    return alloc_field(shape, system, marker.extent, init)
end

"""
    storage_field_type(x)

$(internal_api_warning())

Return the type of a storage field declared as `x`. A [`field_shape`](@ref) is resolved to
its [`container_type`](@ref), everything else is a plain container type and is returned
unchanged. [`@storage`](@ref) wraps every declared field type with this function, so both
kinds of declaration can be mixed freely inside one storage.
"""
storage_field_type(x) = storage_field_type(x, field_shape(x))
storage_field_type(x, ::Nothing) = x
storage_field_type(_, shape::AbstractFieldShape) = container_type(shape)

# --------------------------------------------------------------------------------------
# state of the constitutive model
# --------------------------------------------------------------------------------------

"""
    ConstitutiveState

$(extension_api_note())

Declaration of the storage field that carries the state of the constitutive model:

```julia
Peridynamics.@storage MyMaterial struct MyStorage
    @inherit VelocityVerletFields BondFracFields
    cm_state::ConstitutiveState
end
```

This is not a field shape: the field is not an array, it is whatever the constitutive model
of the material declares with `@cm_storage`, and `nothing` for a model without
state. The generated storage gets one extra type parameter `CMS` for it, which
[`storage_type`](@ref) fills with
`constitutive_storage_type(get_constitutive_model(mat), FT)`, so the storage stays concrete
whichever model is used. The state is reached with `constitutive_state`.

A storage may declare at most one such field, and it cannot be annotated with
[`@lth`](@ref) or [`@htl`](@ref), because the halo exchange does not descend into a nested
field.
"""
struct ConstitutiveState end

# the name of the type parameter the `ConstitutiveState` declaration contributes
const CM_STATE_TYPE_PARAM = :CMS

# --------------------------------------------------------------------------------------
# state of the damage model
# --------------------------------------------------------------------------------------

"""
    DamageState

$(extension_api_note())

Declaration of the storage field that carries the state of the damage model:

```julia
Peridynamics.@storage MyMaterial struct MyStorage
    @inherit VelocityVerletFields BondFracFields
    dmg_state::DamageState
end
```

This is the damage-model twin of [`ConstitutiveState`](@ref): the field is not an array, it
is whatever the damage model of the material declares with `@dmg_storage`, and
`nothing` for a model without state. The generated storage gets one extra type parameter
`DMS` for it, which [`storage_type`](@ref) fills with
`damage_storage_type(get_dmgmodel(mat), FT)`, so the storage stays concrete whichever damage
model is used. The state is reached with `damage_state`.

A material that declares this field supports **every** damage model, stateful or not,
without knowing any of them: a model that needs per-bond variables brings them itself
instead of the material having to allocate them for it.

A storage may declare at most one such field, and it cannot be annotated with
[`@lth`](@ref) or [`@htl`](@ref), because the halo exchange does not descend into a nested
field.
"""
struct DamageState end

# the name of the type parameter the `DamageState` declaration contributes
const DMG_STATE_TYPE_PARAM = :DMS

# --------------------------------------------------------------------------------------
# field annotations
# --------------------------------------------------------------------------------------

#=
The annotations are never expanded. `@storage` and `@storage_fields` recognize them by name
while they parse their body, so they work qualified as well as unqualified. They exist as
macros so that they have a docstring and so that using one outside of a storage definition
is an error instead of an undefined name.

Whether a field is point data follows from its field shape, so the annotations only say how
a field is exchanged between chunks. Both imply halo extent, and both imply point data,
because only point data is exchanged.
=#

"""
    @htl field

$(extension_api_note())

Annotate a field of a [`@storage`](@ref) definition for halo-to-local exchange. It has one
entry per local and halo point, and the halo entries are added to the local entries of the
owning chunk during the simulation.
"""
macro htl(expr)
    return macro_outside_storage_error("@htl")
end

"""
    @lth field

$(extension_api_note())

Annotate a field of a [`@storage`](@ref) definition for local-to-halo exchange. It has one
entry per local and halo point, and the halo entries are updated from the owning chunk
during the simulation.
"""
macro lth(expr)
    return macro_outside_storage_error("@lth")
end

function macro_outside_storage_error(name::AbstractString)
    msg = "`$(name)` is only allowed inside a `@storage` or `@storage_fields` definition!\n"
    return :(throw(ArgumentError($(msg))))
end

# --------------------------------------------------------------------------------------
# field declarations and reusable field blocks
# --------------------------------------------------------------------------------------

"""
    StorageFieldDecl

$(internal_api_warning())

One field declaration of a [`@storage`](@ref) or [`@storage_fields`](@ref) block:
the field `name`, its `annotation` (`:none`, `:lth` or `:htl`), the declared `type`
expression (a container type or a [`field_shape`](@ref)) and the `init` expression of the
declaration, or `nothing` if it does not specify one.
"""
struct StorageFieldDecl
    name::Symbol
    annotation::Symbol
    type::Any
    shape::Any
    init::Any
end

function Base.:(==)(a::StorageFieldDecl, b::StorageFieldDecl)
    return a.name === b.name && a.annotation === b.annotation && a.type == b.type &&
           a.shape == b.shape && a.init == b.init
end

# a field is point data if its shape says so, or if it is exchanged between chunks, because
# only point data is exchanged
@inline function is_point_decl(d::StorageFieldDecl)
    return is_halo_decl(d) || isa(d.shape, AbstractPointFieldShape)
end

@inline is_halo_decl(d::StorageFieldDecl) = d.annotation === :lth || d.annotation === :htl

# a field declared with `ConstitutiveState` is not an array and not point data, it holds the
# state of the constitutive model of the material
@inline is_cm_state_decl(d::StorageFieldDecl) = d.type === ConstitutiveState

# the same for `DamageState`, which holds the state of the damage model
@inline is_dmg_state_decl(d::StorageFieldDecl) = d.type === DamageState

# both nested-state markers behave alike everywhere except in which state they carry
@inline is_nested_state_decl(d::StorageFieldDecl) = is_cm_state_decl(d) || is_dmg_state_decl(d)

@inline function field_extent(d::StorageFieldDecl)
    return is_halo_decl(d) ? HaloPoints() : LocalPoints()
end

const FIELD_ANNOTATIONS = Dict{Symbol,Symbol}(Symbol("@lth") => :lth,
                                              Symbol("@htl") => :htl)

"""
    storage_fields_expr(::Type{T})

$(internal_api_warning())

Return the field declarations of a storage type or of a field block defined with
[`@storage_fields`](@ref) as a `Vector` of [`StorageFieldDecl`](@ref). This is the table
[`@inherit`](@ref) reads at macro expansion time.
"""
function storage_fields_expr(::Type{T}) where {T}
    msg = "`$(T)` does not define any storage fields!\n"
    msg *= "  Only storages defined with `@storage` and field blocks defined with "
    msg *= "`@storage_fields` can be inherited from.\n"
    return throw(ArgumentError(msg))
end

"""
    @storage_fields name begin ... end

$(extension_api_note())

Define a reusable block of storage field declarations that can be included into a
[`@storage`](@ref) definition with [`@inherit`](@ref). The body accepts exactly the same
field declarations as `@storage`, including `@inherit` itself.

The macro defines a marker type `name` and registers the (flattened) field declarations
with [`storage_fields_expr`](@ref).

# Example
```julia
@storage_fields VelocityVerletFields begin
    @lth position::PointVector{Float64}
    displacement::PointVector
    velocity::PointVector
    velocity_half::PointVector
    acceleration::PointVector
    b_int::PointVector
    b_ext::PointVector
end
```
"""
macro storage_fields(name, block)
    macrocheck_input_storage_fields_name(name)
    macrocheck_input_storage_fields_block(block)
    local _decls = get_field_decls(block.args, __module__)
    local _struct = quote
        struct $(esc(name)) <: Peridynamics.AbstractStorageFields end
    end
    local _fields_expr = quote
        function Peridynamics.storage_fields_expr(::Base.Type{$(esc(name))})
            return $(QuoteNode(_decls))
        end
    end
    # the docstring is attached last, so that a `$(block_table(Name))` in it can already read
    # the declarations that were just registered
    local _doc = quote
        Base.@__doc__ $(esc(name))
    end
    return Expr(:block, _struct, _fields_expr, _doc)
end

"""
    @inherit storage_or_field_block

$(extension_api_note())

Include all field declarations of another storage or of a field block defined with
[`@storage_fields`](@ref) into a [`@storage`](@ref) or `@storage_fields` definition. The
inherited fields keep their order and are spliced in at the position of the `@inherit`.

Two `@inherit`s may contribute the same field, as long as they declare it identically. A
field declared in the body itself overrides an inherited field of the same name and keeps
its position, which is how a family changes the annotation of an inherited field, for
example from `b_int::PointVector` to `@htl b_int::PointVector`.

The inherited storage or field block has to be defined by an earlier top-level statement,
and it has to be resolvable in the module of the definition, so field blocks of this
package are written as `Peridynamics.RKCStorage`.

# Example
```julia
Peridynamics.@storage MyMaterial struct MyStorage
    @inherit Peridynamics.RKCStorage
    my_point_field::PointScalar
    my_bond_field::BondScalar
end
```
"""
macro inherit(exprs...)
    return macro_outside_storage_error("@inherit")
end

function resolve_inherited_decls(mod::Module, name_expr)
    inherited_type = resolve_in_mod_or_peridynamics(mod, name_expr)
    if isnothing(inherited_type)
        msg = "cannot resolve `$(name_expr)` of `@inherit`!\n"
        msg *= "  It has to be defined by an earlier top-level statement and it has to be "
        msg *= "resolvable in `$(mod)` or in `Peridynamics`.\n"
        throw(ArgumentError(msg))
    end
    if !isa(inherited_type, Type)
        msg = "`$(name_expr)` of `@inherit` is not a type!\n"
        throw(ArgumentError(msg))
    end
    # `invokelatest` because the method of `storage_fields_expr` for `inherited_type` was
    # defined by a top-level statement that is newer than this macro
    return Base.invokelatest(storage_fields_expr, inherited_type)
end

#=
Names inside a storage definition are resolved in the module of the definition first and in
`Peridynamics` second, so that the field shapes and the storages of this package can be
written unqualified without importing them. This is hygienic because the macro interpolates
the *resolved* types into the generated struct, so no name of this package ends up in the
generated code.
=#
function resolve_in_mod_or_peridynamics(mod::Module, expr)
    resolved = try_eval(mod, expr)
    isnothing(resolved) || return resolved
    mod === Peridynamics && return nothing
    return try_eval(Peridynamics, expr)
end

function try_eval(mod::Module, expr)
    return try
        Core.eval(mod, expr)
    catch
        nothing
    end
end

"""
    get_field_decls(block_args, mod)

$(internal_api_warning())

Parse the body of a [`@storage`](@ref) or [`@storage_fields`](@ref) definition into a
`Vector` of [`StorageFieldDecl`](@ref), expanding every [`@inherit`](@ref) and applying the
merge rules documented there.

Field types and initial values are resolved in `mod` while the macro is expanded, so an
inherited declaration always keeps the meaning it has in the module that declared it.
"""
function get_field_decls(block_args, mod::Module)
    decls = Vector{StorageFieldDecl}()
    sources = Dict{Symbol,String}()
    for field in block_args
        field isa LineNumberNode && continue
        if !isa(field, Expr)
            # a bare symbol is a valid untyped field of a Julia struct, but a storage field
            # always needs a type or a field shape, so it must not be dropped silently
            msg = "unexpected or untyped field: $field\n"
            throw(ArgumentError(msg))
        end
        macro_name = field.head === :macrocall ? get_macro_name(field.args[1]) : nothing
        if macro_name === Symbol("@inherit")
            for inherit_expr in get_inherit_arguments(field)
                source = string(inherit_expr)
                for decl in resolve_inherited_decls(mod, inherit_expr)
                    add_field_decl!(decls, sources, decl, source, true)
                end
            end
        elseif !isnothing(macro_name) && haskey(FIELD_ANNOTATIONS, macro_name)
            annotation = FIELD_ANNOTATIONS[macro_name]
            decl = parse_field_decl(field.args[end], annotation, mod)
            add_field_decl!(decls, sources, decl, "the definition itself", false)
        elseif field.head === :(::) || field.head === :(=)
            decl = parse_field_decl(field, :none, mod)
            add_field_decl!(decls, sources, decl, "the definition itself", false)
        else
            msg = "unexpected or untyped field: $field\n"
            throw(ArgumentError(msg))
        end
    end
    return decls
end

# the annotation macros are never expanded, they are only recognized by name, so they work
# unqualified as well as qualified with `Peridynamics.`
get_macro_name(name::Symbol) = name
get_macro_name(name::GlobalRef) = name.name
function get_macro_name(name::Expr)
    if name.head === :. && length(name.args) == 2 && name.args[2] isa QuoteNode
        return get_macro_name(name.args[2].value)
    end
    return nothing
end
get_macro_name(name) = nothing

function get_inherit_arguments(field::Expr)
    args = filter(x -> !isa(x, LineNumberNode), field.args[2:end])
    if isempty(args)
        msg = "`@inherit` expects at least one storage or field block, got: $(field)\n"
        throw(ArgumentError(msg))
    end
    return args
end

function parse_field_decl(expr, annotation::Symbol, mod::Module)
    init_expr = nothing
    decl = expr
    if decl isa Expr && decl.head === :(=)
        init_expr = decl.args[2]
        decl = decl.args[1]
    end
    if !(decl isa Expr && decl.head === :(::) && decl.args[1] isa Symbol)
        msg = "unexpected or untyped field: $expr\n"
        throw(ArgumentError(msg))
    end
    name, type_expr = decl.args[1], decl.args[2]
    resolved_type = resolve_field_type(mod, type_expr)
    shape = isnothing(resolved_type) ? nothing : field_shape(resolved_type)
    field_type = isnothing(resolved_type) ? type_expr : resolved_type
    init = isnothing(init_expr) ? nothing : resolve_field_init(mod, init_expr)
    if isnothing(shape) && !isnothing(init_expr)
        msg = "the storage field `$(name)` specifies the initial value `$(init_expr)`, "
        msg *= "but is not declared with a field shape!\n"
        msg *= "  Only fields declared with a field shape, e.g. `PointScalar`, can specify "
        msg *= "an initial value. Fields declared with a container type, e.g. "
        msg *= "`Vector{Float64}`, need an `init_field` method instead.\n"
        throw(ArgumentError(msg))
    end
    return StorageFieldDecl(name, annotation, field_type, shape, init)
end

function resolve_field_type(mod::Module, type_expr)
    resolved = resolve_in_mod_or_peridynamics(mod, type_expr)
    return isa(resolved, Type) ? resolved : nothing
end

function resolve_field_init(mod::Module, init_expr)
    resolved = resolve_in_mod_or_peridynamics(mod, init_expr)
    return isnothing(resolved) ? esc(init_expr) : resolved
end

function add_field_decl!(decls::Vector{StorageFieldDecl}, sources::Dict{Symbol,String},
                         decl::StorageFieldDecl, source::AbstractString,
                         from_inherit::Bool)
    idx = findfirst(d -> d.name === decl.name, decls)
    if isnothing(idx)
        push!(decls, decl)
        sources[decl.name] = source
        return nothing
    end
    if !from_inherit
        # a field of the definition itself overrides an inherited field in place
        decls[idx] = decl
        sources[decl.name] = source
        return nothing
    end
    decls[idx] == decl && return nothing
    msg = "conflicting declarations of the storage field `$(decl.name)`!\n"
    msg *= "  inherited from $(sources[decl.name]): $(decl_msg(decls[idx]))\n"
    msg *= "  inherited from $(source): $(decl_msg(decl))\n"
    msg *= "  Declare the field in the storage definition itself to resolve the "
    msg *= "conflict.\n"
    return throw(ArgumentError(msg))
end

function decl_msg(d::StorageFieldDecl)
    msg = d.annotation === :none ? "" : "@$(d.annotation) "
    msg *= "$(d.name)::$(d.type)"
    isnothing(d.init) || (msg *= " = $(d.init)")
    return msg
end

function macrocheck_input_storage_fields_name(name)
    name isa Symbol && return nothing
    msg = "argument `$name` is not a valid field block name!\n"
    return throw(ArgumentError(msg))
end

function macrocheck_input_storage_fields_block(block)
    (block isa Expr && block.head === :block) && return nothing
    msg = "specified input is not a valid field block expression!\n"
    return throw(ArgumentError(msg))
end

# --------------------------------------------------------------------------------------
# type parameters of the generated storage
# --------------------------------------------------------------------------------------

#=
The generated storage struct is parametric in the array type of every field, so that a whole
storage can be moved to another array backend with `Adapt.adapt`, and generic in one float
type `FT`, so that a simulation with a different float type is another instantiation of the
same struct instead of another struct.

One parameter is derived per distinct pair of element type and number of dimensions, in the
order in which the pairs first appear in the declarations, plus a leading `FT` if any field
follows the float type of the simulation. A field that is declared neither with a field
shape nor with an `Array` type, e.g. with an `MArray`, keeps the type it is declared with
and contributes no parameter.
=#

const FLOAT_TYPE_PARAM = :FT

"""
    StorageTypeParam

$(internal_api_warning())

One derived type parameter of a storage generated by [`@storage`](@ref): its `name`, the
element type of the fields it stands for, which is [`SimFloat`](@ref) if they follow the
float type of the simulation, and the number of dimensions `n_dims` of their arrays.
"""
struct StorageTypeParam
    name::Symbol
    eltype::Any
    n_dims::Int
end

"""
    derive_storage_type_params(decls)

$(internal_api_warning())

Derive the type parameters of a storage from its field declarations. Returns the derived
[`StorageTypeParam`](@ref)s in the order they appear in the struct header, a `Dict` that
maps the name of a field to the name of its type parameter, whether any field follows the
float type of the simulation and the header therefore starts with `FT`, and the names of the
fields declared with [`ConstitutiveState`](@ref) and [`DamageState`](@ref), which contribute
the trailing parameters `CMS` and `DMS` in that order.
"""
function derive_storage_type_params(decls)
    params = Vector{StorageTypeParam}()
    field_params = Dict{Symbol,Symbol}()
    uses_sim_float = false
    cm_state_field = nothing
    dmg_state_field = nothing
    for decl in decls
        if is_cm_state_decl(decl)
            isnothing(cm_state_field) || throw(ArgumentError(nested_state_twice_msg(:cm,
                                                                                    cm_state_field,
                                                                                    decl.name)))
            is_halo_decl(decl) && throw(ArgumentError(nested_state_halo_msg(:cm, decl)))
            cm_state_field = decl.name
            field_params[decl.name] = CM_STATE_TYPE_PARAM
            continue
        end
        if is_dmg_state_decl(decl)
            isnothing(dmg_state_field) || throw(ArgumentError(nested_state_twice_msg(:dmg,
                                                                                     dmg_state_field,
                                                                                     decl.name)))
            is_halo_decl(decl) && throw(ArgumentError(nested_state_halo_msg(:dmg, decl)))
            dmg_state_field = decl.name
            field_params[decl.name] = DMG_STATE_TYPE_PARAM
            continue
        end
        key = storage_field_param_key(decl)
        isnothing(key) && continue
        T, n_dims = key
        T === SimFloat && (uses_sim_float = true)
        idx = findfirst(p -> p.eltype === T && p.n_dims == n_dims, params)
        if isnothing(idx)
            push!(params, StorageTypeParam(storage_param_name(params, T, n_dims), T, n_dims))
            idx = lastindex(params)
        end
        field_params[decl.name] = params[idx].name
    end
    return (; params, field_params, uses_sim_float, cm_state_field, dmg_state_field)
end

# `kind` is `:cm` for the constitutive model and `:dmg` for the damage model; the two nested
# states are declared, checked and reported the same way
@inline nested_state_model(kind::Symbol) = kind === :cm ? "constitutive model" : "damage model"
@inline nested_state_marker(kind::Symbol) = kind === :cm ? "ConstitutiveState" : "DamageState"

function nested_state_twice_msg(kind::Symbol, first_field::Symbol, second_field::Symbol)
    msg = "a storage can carry the state of only one $(nested_state_model(kind)), but both "
    msg *= "`$(first_field)` and `$(second_field)` are declared with "
    msg *= "`$(nested_state_marker(kind))`!\n"
    return msg
end

function nested_state_halo_msg(kind::Symbol, decl::StorageFieldDecl)
    msg = "the storage field `$(decl.name)` holds the state of the "
    msg *= "$(nested_state_model(kind)) and cannot be annotated with "
    msg *= "`@$(decl.annotation)`!\n"
    msg *= "  The halo exchange does not descend into a nested field, so the state of a "
    msg *= "$(nested_state_model(kind)) is chunk-local. Bond state and point-local state "
    msg *= "need no exchange.\n"
    return msg
end

# The element type and the number of dimensions a field contributes, or `nothing` for a
# field whose type is not an `Array`, because only an array can be exchanged for the array
# of another backend.
function storage_field_param_key(decl::StorageFieldDecl)
    isnothing(decl.shape) || return (field_eltype(decl.shape), field_n_dims(decl.shape))
    T = decl.type
    (isa(T, Base.Type) && T <: Base.Array && isconcretetype(T)) || return nothing
    return (eltype(T), ndims(T))
end

function storage_param_name(params, ::Base.Type{T}, n_dims::Int) where {T}
    name = Symbol(storage_param_prefix(n_dims), "_", storage_param_suffix(T))
    any(p -> p.name === name, params) || return name
    n = 2
    while any(p -> p.name === Symbol(name, "_", n), params)
        n += 1
    end
    return Symbol(name, "_", n)
end

storage_param_prefix(n_dims::Int) = n_dims == 1 ? "V" : n_dims == 2 ? "M" : "A$(n_dims)"

storage_param_suffix(::Base.Type{SimFloat}) = string(FLOAT_TYPE_PARAM)
storage_param_suffix(::Base.Type{Float64}) = "F64"
storage_param_suffix(::Base.Type{Float32}) = "F32"
storage_param_suffix(::Base.Type{Float16}) = "F16"
storage_param_suffix(::Base.Type{Int64}) = "Int"
storage_param_suffix(::Base.Type{T}) where {T} = isa(T, DataType) ? string(nameof(T)) : "E"

"""
    storage_param_bound(param)

$(internal_api_warning())

Return the type expression a derived type parameter is bounded by in the generated storage
struct, e.g. `AbstractMatrix{FT}` for `M_FT`. The bound is abstract, so that a storage can
hold the arrays of any backend.
"""
function storage_param_bound(param::StorageTypeParam)
    E = storage_param_eltype(param)
    param.n_dims == 1 && return Expr(:curly, Base.AbstractVector, E)
    param.n_dims == 2 && return Expr(:curly, Base.AbstractMatrix, E)
    return Expr(:curly, Base.AbstractArray, E, param.n_dims)
end

"""
    storage_param_default(param)

$(internal_api_warning())

Return the type expression of the array a derived type parameter stands for in a simulation
on the CPU, e.g. `Matrix{FT}` for `M_FT`. This is what [`storage_type`](@ref) instantiates
the storage with.
"""
function storage_param_default(param::StorageTypeParam)
    E = storage_param_eltype(param)
    param.n_dims == 1 && return Expr(:curly, Base.Vector, E)
    param.n_dims == 2 && return Expr(:curly, Base.Matrix, E)
    return Expr(:curly, Base.Array, E, param.n_dims)
end

@inline function storage_param_eltype(param::StorageTypeParam)
    return param.eltype === SimFloat ? FLOAT_TYPE_PARAM : param.eltype
end

"""
    storage_field_decl_type(decl, field_params)

$(internal_api_warning())

Return the type of a field in the generated storage struct, which is the name of its derived
type parameter, or the type it is declared with if it has none.
"""
@inline function storage_field_decl_type(decl::StorageFieldDecl, field_params)
    return get(field_params, decl.name, decl.type)
end
