"""
    force_density_point!(storage, system, mat, params, t, Δt, i)

$(extension_api_note())

Calculate the internal force density of point `i` and accumulate it into
`storage.b_int`. This is the one method a material has to define; everything else about a
material is declared with `@params` and [`@storage`](@ref).

It is called once per local point and per time step, from inside a loop over
[`each_point_idx`](@ref) that runs on every thread and on every MPI rank. A method must
therefore only ever write to the columns of point `i`, and read every other point through
the system; then the same material runs under multithreading and MPI without a change.

# Arguments

- `storage`: The storage of the body chunk, holding every field of the simulation.
- `system`: The system of the body chunk, e.g. a [`BondSystem`](@ref). Dispatch on it to say
    which discretization the material is written for.
- `mat`: The material.
- `params`: The point parameters of point `i`. When a body has several parameter sets, the
    fallback resolves them with [`get_params`](@ref) before calling this method, so a method
    only ever sees one set.
- `t::Real`: The current simulation time.
- `Δt::Real`: The current time step.
- `i::Int`: The index of the local point that is evaluated.

# Example

A bond-based material, in full:

```julia
function Peridynamics.force_density_point!(storage, system::Peridynamics.BondSystem,
                                           mat::MyMaterial, params, t, Δt, i)
    for bond_id in Peridynamics.each_bond_idx(system, i)
        bond = system.bonds[bond_id]
        j, L = bond.neighbor, bond.length

        ΔXij = Peridynamics.get_vector_diff(system.position, i, j)
        Δxij = Peridynamics.get_vector_diff(storage.position, i, j)
        l = norm(Δxij)
        ε = (l - L) / L

        # the damage model decides whether the bond is still there
        stretch_based_failure!(storage, system, bond, params, ε, i, bond_id)

        b = storage.bond_active[bond_id] * params.bc * ε / l .* Δxij
        Peridynamics.update_add_vector!(storage.b_int, i, b .* system.volume[j])
    end
    return nothing
end
```

See also [`storage_type`](@ref), [`get_params`](@ref), [`each_bond_idx`](@ref).
"""
function force_density_point! end

"""
    storage_type(mat)
    storage_type(mat, ::Type{FT})

$(extension_api_note())

Return the storage type of a material, instantiated for the float type `FT` of the
simulation. The storage generated by [`@storage`](@ref) is parametric in the array type of
every field, and this method returns the instantiation with the arrays of the CPU, so that
`body_chunk_type` and everything built from it stay concrete.
"""
function storage_type(mat::AbstractMaterial)
    return throw(InterfaceError(mat, "storage_type", storage_macro_hint(mat)))
end

function storage_macro_hint(mat)
    name = mat isa Type ? nameof(mat) : nameof(typeof(mat))
    msg = "Declare the storage of `$(name)` with `@storage`, e.g.\n"
    msg *= "        Peridynamics.@storage $(name) struct MyStorage\n"
    msg *= "            @inherit VelocityVerletFields BondFracFields\n"
    msg *= "            my_field::PointScalar\n"
    msg *= "        end\n"
    msg *= "    which defines `storage_type` and `get_storage` for you."
    return msg
end

# a storage that is not generic in its float type, i.e. one that is not generated by
# `@storage`, ignores the requested float type
storage_type(mat::AbstractMaterial, ::Type) = storage_type(mat)

function get_storage(material, solver, system)
    return throw(InterfaceError(material, "get_storage", storage_macro_hint(material)))
end

"""
    init_field(material, solver, system, ::Val{field})

$(extension_api_note())

Return the initial value of a storage field. Every field of a storage generated by
[`@storage`](@ref) is allocated by this function, in this order:

1. the system, which owns `position` and the fields of the fracture bookkeeping,
2. the field shape of a field declared with [`@lth`](@ref) or [`@htl`](@ref), because
   whether a field has halo entries is storage knowledge that a time solver cannot have,
3. the time solver, which says whether it needs the field and at which extent,
4. the field shape of every other declared field,
5. an `InterfaceError` that asks for an `init_field` method.

A method of this function for a specific material is more specific than the fallback above
and therefore wins, which is the escape hatch for a field that no field shape describes and
for a shaped field that has to be filled by hand.
"""
function init_field(material, solver, system, field)
    Storage = storage_type(material, float_type(system))
    field_value_system = init_field_system(system, field)
    isnothing(field_value_system) || return field_value_system
    field_value_halo = init_field_storage(Storage, system, field, HaloPoints())
    isnothing(field_value_halo) || return field_value_halo
    field_value_solver = resolve_solver_field(init_field_solver(solver, system, field),
                                              Storage, system, field)
    isnothing(field_value_solver) || return field_value_solver
    field_value_storage = init_field_storage(Storage, system, field, LocalPoints())
    isnothing(field_value_storage) || return field_value_storage
    method_msg = "init_field(::$(typeof(material)), "
    method_msg *= "::$(typeof(solver)), "
    method_msg *= "::$(typeof(system)), "
    method_msg *= "::$(typeof(field)))"
    return throw(InterfaceError(material, method_msg, init_field_hint(field)))
end

#=
A time solver answers `init_field_solver` either with one of the markers of
`core/storage_fields.jl`, which is how every solver of this package does it, or with the
field itself, which is how a third party solver allocates a field that no field shape
describes. Anything that is not a marker is passed through unchanged, including the
`nothing` of a solver that has nothing to say about the field.
=#
@inline resolve_solver_field(field_value, Storage, system, field) = field_value

@inline function resolve_solver_field(::EmptyField, Storage, system, field)
    return alloc_empty_field(Storage, field)
end

@inline function resolve_solver_field(marker::FullField, Storage, system, field)
    field_value = init_field_storage(Storage, system, field, marker)
    isnothing(field_value) && throw(ArgumentError(unshaped_field_msg(Storage, field)))
    return field_value
end

function unshaped_field_msg(::Type{S}, ::Val{Field}) where {S,Field}
    msg = "the time solver needs the storage field `$(Field)`, but `$(nameof(S))` declares "
    msg *= "it with a container type!\n"
    msg *= "  Only a field declared with a field shape can be sized by a time solver. "
    msg *= "Declare it with the shape it has, e.g.\n"
    msg *= "        $(Field)::PointVector\n"
    msg *= "    or inherit it from the field block of the time solver, e.g.\n"
    msg *= "        @inherit VelocityVerletFields\n"
    msg *= "    or define an `init_field` method that allocates it.\n"
    return msg
end

"""
    init_field_storage(::Type{Storage}, system, field, extent)

$(internal_api_warning())

Return the value of `field` as it follows from the field shape it was declared with in the
[`@storage`](@ref) definition of `Storage`, or `nothing` if the field was declared with a
plain container type or does not have the requested `extent`. Methods of this function are
generated by `@storage`, so a field declared with a field shape never needs an
[`init_field`](@ref) method.
"""
@inline function init_field_storage(::Type, system, field, extent)
    return nothing
end

function init_field_hint(::Val{Field}) where {Field}
    msg = "Either declare `$(Field)` with a field shape in the `@storage` definition, "
    msg *= "e.g.\n"
    msg *= "        $(Field)::PointScalar\n"
    msg *= "    or inherit it from the storage of the material family, e.g.\n"
    msg *= "        @inherit RKCStorage\n"
    msg *= "    or define the `init_field` method shown above."
    return msg
end

init_field_hint(field) = ""

"""
    @storage material storage
    @storage material solver storage

$(extension_api_note())

A macro for automatic creation of a storage type. The macro then maps a specified `material`
type with the `storage` structure. When no solver is specified, this storage is always used
independently of the solver type. Specifying a solver allows the usage of customized
storages for a solver.

# Declaring a field

A field is declared with a **field shape**, which says what the field *is*. The shape
determines the container type, the element type and the allocation, so a field declared with
a shape needs no [`init_field`](@ref) method:

| shape | container | rows | entries |
|:---|:---|:---|:---|
| [`PointScalar`](@ref) | `Vector` | – | points |
| [`PointVector`](@ref) | `Matrix` | `get_n_dim(system)` | points |
| [`PointTensor`](@ref) | `Matrix` | `get_n_dim(system)^2` | points |
| [`PointSymTensor`](@ref) | `Matrix` | `d * (d + 1) ÷ 2` | points |
| [`PointField{N}`](@ref PointField) | `Matrix` | `N` | points |
| [`BondScalar`](@ref) | `Vector` | – | bonds |
| [`BondVector`](@ref) | `Matrix` | `get_n_dim(system)` | bonds |
| [`BondTensor`](@ref) | `Matrix` | `get_n_dim(system)^2` | bonds |
| [`BondSymTensor`](@ref) | `Matrix` | `d * (d + 1) ÷ 2` | bonds |
| [`BondField{N}`](@ref BondField) | `Matrix` | `N` | bonds |
| [`DofVector`](@ref) | `Vector` | – | degrees of freedom |

Everything that depends on the spatial dimension goes through `get_n_dim(system)`, so a
shaped field needs no change when a system of a different dimension is added.

A **point shape makes the field point data**, which is what can be exported to VTK files. A
bond or dof shape is not point data.

## Element type

A shape written without an element type follows the float type of the simulation, see
[`SimFloat`](@ref). A shape with an element type pins it for every simulation, which is why
`position` is declared `PointVector{Float64}`: bond vectors are position differences and a
smaller float type loses them over a large domain. `PointScalar{Bool}` and
`PointScalar{Int}` are the non-float cases.

## Annotations

Only the halo exchange is annotated, everything else follows from the shape. Both
annotations give the field one entry per local *and* halo point:

- `@lth`: local-to-halo exchange during the simulation, i.e. the halo entries are updated
    from the chunk that owns the points.
- `@htl`: halo-to-local exchange, i.e. the halo entries are added to the local entries of
    the owning chunk.
- `@inherit`: includes all fields of one or more other storages or of field blocks defined
    with [`@storage_fields`](@ref). See [`@inherit`](@ref) for the merge rules.

## Initial value

The initial value of a shaped field is written `= value`:

| written | result |
|:---|:---|
| omitted | zeros |
| a `Number`, e.g. `= 1.0` or `= true` | every entry that value |
| a `LinearAlgebra.UniformScaling`, e.g. `= I` or `= 2I` | every column that tensor |

A `UniformScaling` requires a shape whose rows are the entries of a square tensor, e.g.
`PointTensor`.

## Anything a shape does not describe

A field can also be declared with a plain container type, e.g.
`zem_stiffness::MArray{NTuple{4,3},Float64,4,81}`. Such a field is not point data and it
needs an [`init_field`](@ref) method that allocates it. A container type that is an `Array`,
e.g. `Vector{Float64}`, still takes part in the type parameters described below, everything
else keeps the type it is declared with.

A field that a time solver works with is the one case where a container type is not enough.
A solver says only whether it needs the field and at which extent and leaves the number of
rows and the element type to the shape, so it cannot size a container-typed field.
Inheriting the field block of the solver, e.g. `@inherit VelocityVerletFields`, declares
all of them with the right shape.

An `init_field` method is also the escape hatch for a *shaped* field: it is more specific
than the generic fallback and therefore wins, so a field can keep its shape — and with it
its type, its size and its export status — while being filled by hand:

````julia
function Peridynamics.init_field(::MyMaterial, ::Peridynamics.AbstractTimeSolver,
                                 system::Peridynamics.AbstractSystem, ::Val{:my_field})
    return ...
end
````

# The generated type

The generated struct must not declare type parameters of its own, because the macro derives
them from the declarations: one parameter per distinct combination of element type and
number of dimensions, plus a leading `FT` for the float type of the simulation. The storage
of the bond-based material below becomes

````julia
struct BBStorage{FT<:Real,M_F64<:AbstractMatrix{Float64},M_FT<:AbstractMatrix{FT},
                 V_FT<:AbstractVector{FT},V_Int<:AbstractVector{Int},
                 V_Bool<:AbstractVector{Bool}} <: AbstractStorage
    position::M_F64
    displacement::M_FT
    ...
end
````

so `storage_type(mat)` returns the instantiation with the arrays of the CPU,
`storage_type(mat, Float32)` the one with `Float32` arrays, and `Adapt.adapt(backend, s)`
moves a whole storage to another array backend. Dispatch on the storage therefore has to be
written `::Type{<:BBStorage}` instead of `::Type{BBStorage}`, while `::BBStorage` is
unchanged.

# Example
Example definition of the storage for the bond-based material:
````julia
@storage BBMaterial struct BBStorage <: AbstractStorage
    @inherit VelocityVerletFields DynamicRelaxationFields NewtonKrylovFields BondFracFields
    strain_energy_density::PointScalar
    bond_length::BondScalar
end
````
"""
macro storage end

macro storage(material, storage)
    macrocheck_input_material(material)
    macrocheck_input_storage_struct(storage)
    return __storage(material, storage, __module__)
end

macro storage(material, solver, storage)
    macrocheck_input_material(material)
    macrocheck_input_timesolver(solver)
    macrocheck_input_storage_struct(storage)
    return __storage(material, storage, __module__, solver)
end

function __storage(material, storage, mod::Module, timesolver=AbstractTimeSolver)
    local _storage_struct_data = get_storage_structdef(storage, mod)
    local _storage_struct = _storage_struct_data.storage_struct
    local _storage_type = _storage_struct_data.storage_type
    local _decls = _storage_struct_data.decls
    local _params = _storage_struct_data.params
    local _uses_sim_float = _storage_struct_data.uses_sim_float
    local _cm_state_field = _storage_struct_data.cm_state_field
    local _dmg_state_field = _storage_struct_data.dmg_state_field

    local _point_field_names = Tuple(QuoteNode(d.name) for d in _decls if is_point_decl(d))
    local _htl_field_names = Tuple(QuoteNode(d.name)
                                   for d in _decls if d.annotation === :htl)
    local _lth_field_names = Tuple(QuoteNode(d.name)
                                   for d in _decls if d.annotation === :lth)
    local _halo_field_names = (_htl_field_names..., _lth_field_names...)

    # one literal `Val` per field instead of one built from a runtime `Symbol`, so that
    # every `init_field` call is resolved at compile time and the whole construction of a
    # storage is type stable
    local _init_field_calls = [
        if is_cm_state_decl(_decl)
            # the state of the constitutive model is not a field of the storage in the sense
            # of `init_field`: it is allocated by the model, not by the system or the solver
            :(Peridynamics.init_constitutive_state(mat, solver, system))
        elseif is_dmg_state_decl(_decl)
            # the same for the state of the damage model
            :(Peridynamics.init_damage_state(mat, solver, system))
        else
            :(Peridynamics.init_field(mat, solver, system,
                                      Base.Val($(QuoteNode(_decl.name)))))
        end
        for _decl in _decls
    ]

    local _constructor = quote
        function $(esc(_storage_type))(mat::$(esc(material)), solver::$(esc(timesolver)),
                                       system::Peridynamics.AbstractSystem)
            return $(esc(_storage_type))($(_init_field_calls...))
        end
    end

    local _storage_type_function = storage_type_function(material, _storage_type, _params,
                                                         _uses_sim_float, _cm_state_field,
                                                         _dmg_state_field)

    local _constitutive_state = if isnothing(_cm_state_field)
        Expr(:block)
    else
        quote
            @inline function Peridynamics.constitutive_state(s::$(esc(_storage_type)))
                return Base.getfield(s, $(QuoteNode(_cm_state_field)))
            end
            function Peridynamics.has_constitutive_state(::Base.Type{<:$(esc(_storage_type))})
                return true
            end
        end
    end

    local _damage_state = if isnothing(_dmg_state_field)
        Expr(:block)
    else
        quote
            @inline function Peridynamics.damage_state(s::$(esc(_storage_type)))
                return Base.getfield(s, $(QuoteNode(_dmg_state_field)))
            end
            function Peridynamics.has_damage_state(::Base.Type{<:$(esc(_storage_type))})
                return true
            end
        end
    end

    #=
    Moving a storage to another array backend is a matter of moving every field, because the
    struct is parametric in the array type of each of them and its outer constructor
    re-infers the parameters. A storage without a derived type parameter has nothing that
    could be moved, and rebuilding it would convert the adapted fields back, so it gets no
    method.
    =#
    local _adapt_args = [
        :(Adapt.adapt(to, Base.getfield(s, $(QuoteNode(_decl.name))))) for _decl in _decls
    ]
    local _adapt_structure = if isempty(_params)
        Expr(:block)
    else
        quote
            function Adapt.adapt_structure(to, s::$(esc(_storage_type)))
                return $(esc(_storage_type))($(_adapt_args...))
            end
        end
    end

    local _get_storage = quote
        function Peridynamics.get_storage(mat::$(esc(material)), solver::$(esc(timesolver)),
                                          system::Peridynamics.AbstractSystem)
            return $(esc(_storage_type))(mat, solver, system)
        end
    end

    local _point_data_fields = [
        quote
            function Peridynamics.point_data_field(s::$(esc(_storage_type)),
                                                   ::Val{$(_field)})
                return Base.getfield(s, $(_field))
            end
        end
        for _field in _point_field_names
    ]

    local _get_all_point_data_fields = quote
        function Peridynamics.point_data_fields(::Base.Type{<:$(esc(_storage_type))})
            return $(Expr(:tuple, _point_field_names...))
        end
    end

    local _halo_to_loc_fields = quote
        function Peridynamics.halo_to_loc_fields(::$(esc(_storage_type)))
            return $(Expr(:tuple, _htl_field_names...))
        end
    end

    local _loc_to_halo_fields = quote
        function Peridynamics.loc_to_halo_fields(::$(esc(_storage_type)))
            return $(Expr(:tuple, _lth_field_names...))
        end
    end

    local _is_halo_fields = [
        quote
            function Peridynamics.is_halo_field(::$(esc(_storage_type)), ::Val{$(_field)})
                return true
            end
        end
        for _field in _halo_field_names
    ]

    local _storage_fields_expr = quote
        function Peridynamics.storage_fields_expr(::Base.Type{<:$(esc(_storage_type))})
            return $(QuoteNode(_decls))
        end
    end

    local _init_field_storages = [
        quote
            function Peridynamics.init_field_storage(::Base.Type{<:$(esc(_storage_type))},
                                                     system::Peridynamics.AbstractSystem,
                                                     ::Val{$(QuoteNode(_decl.name))},
                                                     extent::$(typeof(field_extent(_decl))))
                return $(init_field_storage_call(_decl))
            end
            function Peridynamics.init_field_storage(::Base.Type{<:$(esc(_storage_type))},
                                                     system::Peridynamics.AbstractSystem,
                                                     ::Val{$(QuoteNode(_decl.name))},
                                                     marker::Peridynamics.FullField)
                return $(alloc_solver_field_call(_decl))
            end
        end
        for _decl in _decls if !isnothing(_decl.shape)
    ]

    local _checks = quote
        Peridynamics.typecheck_material($(esc(material)))
        Peridynamics.typecheck_storage($(esc(material)), $(esc(_storage_type)))
    end

    local _exprs = Expr(:block, _storage_struct, _constructor, _storage_type_function,
                        _get_storage, _adapt_structure, _point_data_fields...,
                        _get_all_point_data_fields, _halo_to_loc_fields, _loc_to_halo_fields,
                        _is_halo_fields..., _storage_fields_expr, _init_field_storages...,
                        _constitutive_state, _damage_state, _checks)
    return _exprs
end

#=
`storage_type` returns the instantiation of the storage with the arrays of the CPU, which is
what a simulation that does not move its data anywhere else uses, and it takes the float type
of the simulation, which is the only parameter that is not fixed by the field declarations.
=#
function storage_type_function(material, storage_type, params, uses_sim_float,
                               cm_state_field=nothing, dmg_state_field=nothing)
    has_cm_state = !isnothing(cm_state_field)
    has_dmg_state = !isnothing(dmg_state_field)
    has_state = has_cm_state || has_dmg_state
    instantiation = if isempty(params) && !has_state
        esc(storage_type)
    else
        args = Any[esc(storage_type)]
        uses_sim_float && push!(args, FLOAT_TYPE_PARAM)
        append!(args, storage_param_default(param) for param in params)
        # the nested states are the parameters that do not follow from the declarations,
        # because it is the constitutive model and the damage model of the material that
        # answer them; the order matches `storage_header_expr`
        has_cm_state && push!(args, :(Peridynamics.constitutive_storage_type(Peridynamics.get_constitutive_model(mat),
                                                                            $(FLOAT_TYPE_PARAM))))
        has_dmg_state && push!(args, :(Peridynamics.damage_storage_type(Peridynamics.get_dmgmodel(mat),
                                                                        $(FLOAT_TYPE_PARAM))))
        Expr(:curly, args...)
    end
    (uses_sim_float || has_state) || return quote
        function Peridynamics.storage_type(mat::$(esc(material)),
                                           ::Base.Type=Peridynamics.default_float_type())
            return $(instantiation)
        end
    end
    return quote
        function Peridynamics.storage_type(mat::$(esc(material)),
                                           ::Base.Type{$(FLOAT_TYPE_PARAM)}=Peridynamics.default_float_type()) where {$(FLOAT_TYPE_PARAM)}
            return $(instantiation)
        end
    end
end

function init_field_storage_call(decl::StorageFieldDecl)
    args = Any[:(Peridynamics.alloc_field), decl.shape, :system, :extent]
    isnothing(decl.init) || push!(args, decl.init)
    return Expr(:call, args...)
end

function alloc_solver_field_call(decl::StorageFieldDecl)
    args = Any[:(Peridynamics.alloc_solver_field), :marker, decl.shape, :system,
               field_extent(decl), decl.init]
    return Expr(:call, args...)
end

function get_storage_structdef(storage_expr, mod::Module,
                               default_supertype=:(Peridynamics.AbstractStorage))
    storage_type, supertype = get_storage_header(storage_expr, default_supertype)
    decls = get_field_decls(storage_expr.args[3].args, mod)
    (; params, field_params, uses_sim_float, cm_state_field,
       dmg_state_field) = derive_storage_type_params(decls)
    fields_exprs = [Expr(:(::), d.name, storage_field_decl_type(d, field_params))
                    for d in decls]
    fields_block = Expr(:block, fields_exprs...)
    header = storage_header_expr(storage_type, supertype, params, uses_sim_float,
                                 cm_state_field, dmg_state_field)
    storage_struct = Expr(:struct, storage_expr.args[1], header, fields_block)
    return (; storage_struct, storage_type, decls, params, uses_sim_float, cm_state_field,
            dmg_state_field)
end

"""
    storage_header_expr(storage_type, supertype, params, uses_sim_float)

$(internal_api_warning())

Assemble the header of the generated storage struct from the derived type parameters, see
[`derive_storage_type_params`](@ref). A storage without a derived parameter, i.e. one whose
fields are all declared with a type that is not an `Array`, keeps a plain header.
"""
function storage_header_expr(storage_type, supertype, params, uses_sim_float,
                             cm_state_field=nothing, dmg_state_field=nothing)
    param_exprs = Any[]
    uses_sim_float && push!(param_exprs, Expr(:(<:), FLOAT_TYPE_PARAM, Real))
    for param in params
        push!(param_exprs, Expr(:(<:), param.name, storage_param_bound(param)))
    end
    # a nested state is whatever the model declares, so its parameter is unbounded;
    # `Nothing` for a model without state. `CMS` comes before `DMS`.
    isnothing(cm_state_field) || push!(param_exprs, CM_STATE_TYPE_PARAM)
    isnothing(dmg_state_field) || push!(param_exprs, DMG_STATE_TYPE_PARAM)
    isempty(param_exprs) && return Expr(:(<:), storage_type, supertype)
    return Expr(:(<:), Expr(:curly, storage_type, param_exprs...), supertype)
end

"""
    get_storage_header(storage_expr)

$(internal_api_warning())

Return the name and the supertype of the storage struct of a [`@storage`](@ref) definition.
A definition that declares its own type parameters is rejected, because `@storage` derives
them from the field declarations.
"""
function get_storage_header(storage_expr, default_supertype=:(Peridynamics.AbstractStorage))
    header = storage_expr.args[2]
    if header isa Symbol
        # case `struct MyStorage`
        return header, default_supertype
    elseif header isa Expr && header.head === :(<:) && header.args[1] isa Symbol
        # case `struct MyStorage <: AbstractStorage`
        return header.args[1], header.args[2]
    end
    return throw(ArgumentError(storage_header_msg(header)))
end

function storage_header_msg(header)
    is_parametric = header isa Expr &&
                    (header.head === :curly ||
                     (header.head === :(<:) && header.args[1] isa Expr &&
                      header.args[1].head === :curly))
    is_parametric || return "storage header `$(header)` not supported!\n"
    msg = "a storage cannot declare its own type parameters, got `$(header)`!\n"
    msg *= "  `@storage` derives the type parameters of a storage from its field "
    msg *= "declarations, so that the storage is generic in the float type of the "
    msg *= "simulation and can be moved to another array backend. Declare the storage "
    msg *= "without type parameters and pin the element type of a field in its field shape "
    msg *= "instead, e.g.\n"
    msg *= "        position::PointVector{Float64}\n"
    return msg
end

function loc_to_halo_fields(storage)
    return throw(InterfaceError(storage, "loc_to_halo_fields"))
end

function halo_to_loc_fields(storage)
    return throw(InterfaceError(storage, "halo_to_loc_fields"))
end

is_halo_field(::AbstractStorage, ::Val{F}) where {F} = false

macro halo_fields(storage, fields...)
    macrocheck_input_storage_type(storage)
    macrocheck_input_fields(fields...)
    local _checks = quote
        Peridynamics.typecheck_is_storage($(esc(storage)))
        Peridynamics.typecheck_storage_fields($(esc(storage)), $(Expr(:tuple, fields...)))
    end
    local _is_halo_fields = [quote
                                 function Peridynamics.is_halo_field(::$(esc(storage)),
                                                                     ::Val{$(esc(_field))})
                                     return true
                                 end
                             end
                             for _field in fields]
    # the checks have to come last; otherwise errors cannot be tested with @test_throws ...
    return Expr(:block, _is_halo_fields..., _checks)
end

function macrocheck_input_storage_type(storage)
    storage isa Symbol && return nothing
    (storage isa Expr && storage.head === :.) && return nothing
    (storage isa Expr && storage.head === :escape) && return nothing
    msg = "argument `$storage` is not a valid storage input!\n"
    return throw(ArgumentError(msg))
end

function macrocheck_input_storage_struct(storage)
    (storage isa Expr && storage.head === :struct) && return nothing
    (storage isa Expr && storage.head === :escape) && return nothing
    msg = "specified input is not a valid point parameter struct expression!\n"
    return throw(ArgumentError(msg))
end

function macrocheck_input_timesolver(timesolver)
    timesolver isa Symbol && return nothing
    (timesolver isa Expr && timesolver.head === :.) && return nothing
    msg = "argument `$timesolver` is not a valid time solver input!\n"
    return throw(ArgumentError(msg))
end

function macrocheck_input_fields(fields...)
    for field in fields
        macrocheck_input_field(field)
    end
    return nothing
end

function macrocheck_input_field(field)
    if !(field isa QuoteNode && field.value isa Symbol)
        msg = "argument $field is not a valid field input!\n"
        throw(ArgumentError(msg))
    end
    return nothing
end

function typecheck_storage(::Type{Material}, ::Type{Storage}) where {Material,Storage}
    typecheck_is_storage(Storage)
    typecheck_req_fields_missing(Storage, required_fields(Material))
    return nothing
end

function typecheck_storage(material, storage)
    return throw(ArgumentError("$storage is not a valid storage type!\n"))
end

function typecheck_is_storage(::Type{Storage}) where {Storage}
    if !(Storage <: AbstractStorage)
        msg = "$Storage is not a valid storage type!\n"
        throw(ArgumentError(msg))
    end
    return nothing
end

function typecheck_is_storage(storage)
    return throw(ArgumentError("$storage is not a valid storage type!\n"))
end

function typecheck_storage_fields(::Type{S}, fields::NTuple{N,Symbol}) where {S,N}
    storage_fields = fieldnames(S)
    for field in fields
        if !in(field, storage_fields)
            msg = "storage $(S) has no field `$(field)`!\n"
            throw(ArgumentError(msg))
        end
    end
    return nothing
end

function typecheck_req_fields_missing(::Type{Storage}, req_fields) where {Storage}
    storage_fields = fieldnames(Storage)
    for req_field in req_fields
        if !in(req_field, storage_fields)
            error("required field $req_field not found in $(Storage)!\n")
        end
    end
    return false
end

"""
    required_fields(::Type{Material})

$(internal_api_warning())

Return all storage fields that can be determined from the material *type* alone. This is
the cheap check done by [`@storage`](@ref) at macro expansion time.

Everything that depends on the material *instance*, the damage model or the time solver
cannot be known here and is therefore checked at setup time with
[`check_storage_contract`](@ref).
"""
function required_fields(::Type{Material}) where {Material<:AbstractMaterial}
    return required_fields_fracture(Material)
end

"""
    req_storage_fields(mat)
    req_storage_fields(mat, dmgmodel)
    req_storage_fields(solver)

$(internal_api_warning())

Return the storage fields that are required by a material family, by a damage model in
combination with a material, or by a time solver. All methods return a `Tuple` of `Symbol`s
and default to an empty tuple, so only the parts of the contract that really exist have to
be declared.

These declarations are collected by [`check_storage_contract`](@ref) when a [`Job`](@ref)
is created.

# Example
```julia
Peridynamics.req_storage_fields(::MyMaterialFamily) = (:defgrad, :weighted_volume)
Peridynamics.req_storage_fields(::MyMaterialFamily, ::MyDamageModel) = (:bond_damage,)
```
"""
function req_storage_fields end

req_storage_fields(::AbstractMaterial) = ()

"""
    storage_contract(mat::AbstractMaterial, solver::AbstractTimeSolver)

$(internal_api_warning())

Return the complete storage contract of `mat` in combination with `solver` as a `Tuple` of
`(fields, reason)` pairs, where `reason` describes why the fields are required.
"""
function storage_contract(mat::AbstractMaterial, solver::AbstractTimeSolver)
    M, S = typeof(mat), typeof(solver)
    dmgmodel = get_dmgmodel(mat)
    return ((required_fields_fracture(M), "the system of `$(nameof(M))`"),
            (req_storage_fields(mat), "the material `$(nameof(M))`"),
            (req_storage_fields(mat, dmgmodel), "the damage model `$(_name_of(dmgmodel))`"),
            (req_storage_fields(solver), "the time solver `$(nameof(S))`"))
end

@inline _name_of(x) = nameof(typeof(x))
@inline _name_of(::Nothing) = :Nothing

"""
    check_storage_contract(spatial_setup, solver::AbstractTimeSolver)

$(internal_api_warning())

Check if the storage of every material of `spatial_setup` contains all fields that are
required by the material itself, by its damage model and by the time solver `solver`.
Throws a [`StorageContractError`](@ref) that names the missing fields and the reason why
they are required.

This check is done once when a [`Job`](@ref) is created. In contrast to the check inside
[`@storage`](@ref), the damage model and the time solver are known here, so the parts of
the contract that depend on them can finally be verified.
"""
function check_storage_contract(mat::AbstractMaterial, solver::AbstractTimeSolver)
    S = storage_type(mat)
    storage_fields = fieldnames(S)
    missing_fields = Vector{Pair{Symbol,String}}()
    for (fields, reason) in storage_contract(mat, solver)
        for field in fields
            in(field, storage_fields) && continue
            any(x -> first(x) === field, missing_fields) && continue
            push!(missing_fields, field => reason)
        end
    end
    isempty(missing_fields) && return nothing
    throw(StorageContractError(S, typeof(mat), typeof(solver), missing_fields))
end

function check_storage_contract(body::AbstractBody, solver::AbstractTimeSolver)
    return check_storage_contract(body.mat, solver)
end

function check_storage_contract(ms::AbstractMultibodySetup, solver::AbstractTimeSolver)
    for body in each_body(ms)
        check_storage_contract(body, solver)
    end
    return nothing
end

@inline function get_point_data(s::AbstractStorage, field::Symbol)
    return point_data_field(s, Val(field))
end

function point_data_field(::S, ::Val{Field}) where {S,Field}
    return throw(InterfaceError(S, "point_data_field(::$S, ::Val{$Field})"))
end

function point_data_fields(::Type{S}) where {S<:AbstractStorage}
    return throw(InterfaceError(S, "point_data_fields(::Type{$S})"))
end

function get_loc_to_halo_fields(s::AbstractStorage)
    return Tuple(get_point_data(s, field) for field in loc_to_halo_fields(s))
end

function get_halo_to_loc_fields(s::AbstractStorage)
    return Tuple(get_point_data(s, field) for field in halo_to_loc_fields(s))
end

function get_halo_fields(s::S) where {S<:AbstractStorage}
    return Tuple(get_point_data(s, f) for f in fieldnames(S) if is_halo_field(s, Val(f)))
end

function get_halo_fieldnames(s::S) where {S<:AbstractStorage}
    return Tuple(f for f in fieldnames(S) if is_halo_field(s, Val(f)))
end

function get_n_halo_fields(s::S) where {S<:AbstractStorage}
    n_halo_fields = 0
    for f in fieldnames(S)
        if is_halo_field(s, Val(f))
            n_halo_fields += 1
        end
    end
    return n_halo_fields
end

function get_loc_point_data(storage::AbstractStorage, system::AbstractSystem, field::Symbol)
    val_field = Val(field)
    is_halo_field(storage, val_field) || return point_data_field(storage, val_field)
    return get_loc_view(point_data_field(storage, val_field), system)
end
