# # [Writing your own material](@id tutorial_custom_material)

# This tutorial adds a bond-based material with a conical micro-modulus, written against the
# [Extension API](@ref). The same file runs single-threaded, with `julia -t 6`, and under
# `mpiexec -n 6 julia --project` without a change. The tutorials
# [Writing your own damage model](@ref tutorial_custom_damage_model) and
# [Writing your own constitutive model](@ref tutorial_custom_constitutive_model) build on it.

using Peridynamics
using Peridynamics: BondSystem, each_bond_idx, get_params, get_n_loc_points,
                    get_vector_diff, update_add_vector!, surface_correction_factor,
                    current_bond_length, bond_is_active, get_neighbor,
                    reference_bond_length, dims

# ## The material
#
# The bond-based formulation that [`BBMaterial`](@ref) implements uses a constant
# micro-modulus, the original choice of [Silling2005](@cite). A **conical** micro-modulus
#
# ```math
# c(\xi) = c_1 \left( 1 - \frac{\xi}{\delta} \right) , \qquad \xi = |\boldsymbol{\Delta X}| ,
# ```
#
# lets the stiffness fall linearly to zero at the horizon instead, studied by
# [Bobaru2009](@cite) and [Ha2010](@cite). The constant ``c_1`` follows from requiring the
# same strain energy as a classical isotropic solid under a homogeneous stretch ``s``,
#
# ```math
# W = \pi s^2 \int_0^\delta c(\xi) \, \xi^3 \, \mathrm{d}\xi \overset{!}{=} \frac{9}{2} K s^2 .
# ```
#
# which gives ``c_1 = 90 K / (\pi \delta^4)``, five times the constant micro-modulus value
# ``18 K / (\pi \delta^4)``. A material needs four things: a type, its point parameters, its
# storage, and the force density calculation.

# ### The type
#
# The supertype decides which system the material runs on, so a bond-based material subtypes
# [`AbstractBondSystemMaterial`](@ref Peridynamics.AbstractBondSystemMaterial), with the
# surface correction as its type parameter. The damage model is a field, since every bond
# system material is asked for one, here the built-in [`CriticalStretch`](@ref).

struct ConicalBBMaterial{Correction,DM} <: Peridynamics.AbstractBondSystemMaterial{Correction}
    dmgmodel::DM
end

function ConicalBBMaterial{C}(; dmgmodel=CriticalStretch()) where {C}
    return ConicalBBMaterial{C,typeof(dmgmodel)}(dmgmodel)
end
ConicalBBMaterial(; kwargs...) = ConicalBBMaterial{NoCorrection}(; kwargs...)

# ### The point parameters
#
# These are the values [`material!`](@ref) assigns to a point set, generated by
# [`@params`](@ref Peridynamics.@params) from one list of declarations. We compose
# `DiscretizationParameters` (`δ`, `rho`) and `BBElasticParameters`, the six elastic constants
# of the ``\nu = 1/4`` variant, derive the bond constant from them, and give the damage
# model's own parameters a place with the marker field `dmg_params`, here `Gc` and `εc`.

Peridynamics.@params ConicalBBMaterial struct ConicalBBPointParameters
    @inherit DiscretizationParameters BBElasticParameters
    @log "conical micro-modulus constant" @derived bc = 90 * K / (π * δ^4)
    dmg_params::DamageParameters
end

# `material!(body; horizon, rho, E, Gc)` now works and rejects anything misspelled, `bc` is
# derived from parameters declared before it, kept out of the keywords, and recorded in the
# simulation log by `@log`. Every bond-system material is asked for a bond constant under
# that name for the stable time step estimate, here the micro-modulus at ``\xi = 0``, its
# largest value, so the estimate is safely conservative.
#
# Which names a right-hand side such as `90 * K / (π * δ^4)` may use is what the inherited
# blocks expose, and every block says so itself:

Peridynamics.DiscretizationParameters

# Everything that can be inherited is listed in [Blocks you can inherit](@ref).
# `@inherit StandardParameters` gives the general elastic parameters instead, for a material
# not restricted to ``\nu = 1/4``.

# ### The storage
#
# The storage holds every field that changes during the simulation, one array per quantity.
# [`@storage`](@ref Peridynamics.@storage) generates the struct, the allocation, the halo
# exchange lists and the `Adapt` rule. `@inherit` pulls in the three time solvers, and the
# fracture bookkeeping belongs to the damage model, marked by `dmg_state::DamageState`. We
# add one bond field of our own to show a custom field reaching a VTK file.

Peridynamics.@storage ConicalBBMaterial struct ConicalBBStorage
    @inherit VelocityVerletFields DynamicRelaxationFields NewtonKrylovFields
    stretch::BondScalar
    dmg_state::DamageState
end

# A field shape such as `BondScalar` says how many entries a field has and how it is
# allocated, so no `init_field` method is needed.

# ### The force density
#
# This is the one function a material has to define. It is called once per **local** point
# and per time step, on every thread and every MPI rank, and only ever writes to the columns
# of point `i`, reading everything else through the system. That is why the same code
# parallelizes.
#
# What a force density may use is described in [Materials](@ref).

function Peridynamics.force_density_point!(storage::ConicalBBStorage, system::BondSystem,
                                           mat::ConicalBBMaterial, paramsetup, t, Δt, i)
    (; volume) = system
    params = get_params(paramsetup, i)
    for bond_id in each_bond_idx(system, i)
        j = get_neighbor(system, bond_id)
        L = reference_bond_length(system, bond_id)

        ## the current bond vector, the current length and the stretch of the bond
        Δxij = get_vector_diff(storage.position, i, j, dims(system))
        l = current_bond_length(storage, system, i, bond_id)
        ε = (l - L) / L
        storage.stretch[bond_id] = ε

        ## the conical micro-modulus: full stiffness at L = 0, zero at the horizon
        c = params.bc * (1 - L / params.δ)

        ## a broken bond carries no force, and the surface correction is 1 for `NoCorrection`
        ω = bond_is_active(storage, system, bond_id) *
            surface_correction_factor(system, bond_id)

        ## the bond force, accumulated into point `i`
        b = ω * c * ε * volume[j] / l .* Δxij
        update_add_vector!(storage.b_int, i, b, dims(system))
    end
    return nothing
end

# Which bonds are broken was decided right before this call by the damage model, which is
# why the force density only multiplies `bond_is_active` in and never breaks anything.

# ### The fracture parameters
#
# A user gives a critical energy release rate ``G_c``, and `CriticalStretch` breaks a bond at
# a critical stretch ``\varepsilon_c``, an integral over all the bonds a unit of crack surface
# cuts,
#
# ```math
# G_c = \frac{\pi \varepsilon_c^2}{2} \int_0^\delta c(\xi) \, \xi^4 \, \mathrm{d}\xi ,
# ```
#
# which depends on the micro-modulus. The default gives
# ``\varepsilon_c = \sqrt{5 G_c / (9 K \delta)}``. For the conical one it works out to
#
# ```math
# G_c = \frac{3}{2} K \delta \varepsilon_c^2
# \qquad \Longleftrightarrow \qquad
# \varepsilon_c = \sqrt{\frac{2 G_c}{3 K \delta}} ,
# ```
#
# about 8.7 % below the default, so using the default would break the body too early,
# silently. The material states the relation, the damage model decides what
# ``\varepsilon_c`` means, and both are dispatched on. Define **both** directions:
# whichever keyword the user gives, the other is derived from it.

Peridynamics.critical_stretch(::CriticalStretch, ::ConicalBBMaterial, δ, K, Gc) =
    sqrt(2 * Gc / (3 * K * δ))

Peridynamics.energy_release_rate(::CriticalStretch, ::ConicalBBMaterial, δ, K, εc) =
    1.5 * K * δ * εc^2

# Nothing else about fracture has to be written. The damage model owns the keywords `Gc` and
# `epsilon_c` and switches fracture off when neither is given, in the default
# [`get_frac_params`](@ref Peridynamics.get_frac_params).

# ### Exporting a field of your own
#
# `stretch` is a bond field, but a VTK file wants one value per point.
# [`export_field`](@ref Peridynamics.export_field) reduces it, and
# [`custom_field`](@ref Peridynamics.custom_field) announces the name so a `Job` accepts it.
#
# We weight the reduction with the same micro-modulus the force uses, so the exported number
# is the stretch the stiffness of the point actually sees.

Peridynamics.custom_field(::Type{<:ConicalBBStorage}, ::Val{:weighted_stretch}) = true

function Peridynamics.export_field(::Val{:weighted_stretch}, mat, system,
                                   storage::ConicalBBStorage, paramsetup, t)
    weighted_stretch = zeros(get_n_loc_points(system))
    for i in eachindex(weighted_stretch)
        (; δ) = get_params(paramsetup, i)
        num, den = 0.0, 0.0
        for bond_id in each_bond_idx(system, i)
            L = reference_bond_length(system, bond_id)
            c = 1 - L / δ
            num += c * storage.stretch[bond_id]
            den += c
        end
        weighted_stretch[i] = iszero(den) ? 0.0 : num / den
    end
    return weighted_stretch
end

# ## Running it
#
# The material is finished. From here on nothing is specific to it. It is used exactly like
# a material that ships with the package.

l, Δx = 0.1, 0.002
pos, vol = uniform_box(l, 0.1l, 0.1l, Δx)
body = Body(ConicalBBMaterial(), pos, vol)
material!(body; horizon=3.015Δx, rho=2700, E=70e9, Gc=100)

# Pull the bar apart at both ends:

point_set!(x -> x < -0.4l, body, :left)
point_set!(x -> x > 0.4l, body, :right)
velocity_bc!(t -> -10.0, body, :left, :x)
velocity_bc!(t -> 10.0, body, :right, :x)

# Ask for our own field alongside the built-in ones:

job = Job(body, VelocityVerlet(steps=200);
          path=joinpath(tempdir(), "custom_material"),
          fields=(:displacement, :damage, :weighted_stretch))

#-
#md # ```julia
#md # submit(job)
#md # ```

# The same file, unchanged, also runs as
#
# ```bash
# julia -t 6 --project tutorial_custom_material.jl        # multithreading
# mpiexec -n 6 julia --project tutorial_custom_material.jl # MPI
# ```
#
# The halo exchange follows from the field declarations automatically.

# ## Where to go next
#
# - [Writing your own damage model](@ref tutorial_custom_damage_model) replaces the failure
#   criterion.
# - [Writing your own constitutive model](@ref tutorial_custom_constitutive_model) is the
#   way to go for a new stress-strain relation on the correspondence materials.
# - [Materials](@ref) for the declaration language in full.
# - [Blocks you can inherit](@ref) for everything `@inherit` accepts.
# - [Extension API](@ref) for every name used here.
# - [API stability](@ref) for what is promised and what is deliberately left internal.
